<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Get in the cloud Get ahead in the compe_5d02bd</name>
   <tag></tag>
   <elementGuidId>ba40d579-1537-4785-8568-c1d38ccb0ad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.banner-text-display > img.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='post']/section/div/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d92b5825-b0ca-45e3-9075-baaa1626ecc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cloud Services</value>
      <webElementGuid>565cdd64-6a92-4fef-bb62-c98b33933462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/RBT/media/RBT-Images/Cloud-Application-Development-Services.png?ext=.png</value>
      <webElementGuid>1556d9d4-488a-4e94-9775-eb3090185c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>46d1a177-6f77-4ae9-8d0f-3dab2ddd62df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[@id=&quot;post&quot;]/main[@id=&quot;post&quot;]/section[@class=&quot;inner-banner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;banner-text row&quot;]/div[@class=&quot;col-sm-6 banner-text-display&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>bac1a69c-fcd1-43e4-9d9a-b86c29424dfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='post']/section/div/div/div[2]/img</value>
      <webElementGuid>cf9bb45a-a419-45a6-9cdd-2a9a06b41ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cloud Services']</value>
      <webElementGuid>122f3520-61f1-4b7a-a0a7-5b37c2d0b1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/img</value>
      <webElementGuid>34dff207-05ac-4e39-a4f2-122ee752e8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Cloud Services' and @src = 'https://demo19xperience13.raybiztech.com/RBT/media/RBT-Images/Cloud-Application-Development-Services.png?ext=.png']</value>
      <webElementGuid>ed436a7e-afec-489c-b5cd-a7f80b2422c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
