<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cloud Services_inner-img-right col-lg-5_76b6be</name>
   <tag></tag>
   <elementGuidId>1bad3eda-7391-4642-b33b-492f69b8920f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.inner-img-right.col-lg-5.col-md-6.center-block.img-responsive.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='post']/div[2]/div/div/div/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a1ad1a61-7ca7-4caf-9356-a7990130f217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cloud Application Development Services</value>
      <webElementGuid>08a69e9e-327f-442b-9f3e-c0ac1d5285fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inner-img-right col-lg-5 col-md-6 center-block img-responsive pull-right</value>
      <webElementGuid>5bab25c1-7dae-4204-984d-c8f3ca901b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/RBT/media/RBT-Images/bigstock-cloud-computing.jpg</value>
      <webElementGuid>4649308e-20ca-4d6f-bdfb-7659cef2ce4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[@id=&quot;post&quot;]/main[@id=&quot;post&quot;]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;inrtxt&quot;]/img[@class=&quot;inner-img-right col-lg-5 col-md-6 center-block img-responsive pull-right&quot;]</value>
      <webElementGuid>bc440b89-f570-4d1e-b9e8-e93619946db8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='post']/div[2]/div/div/div/div/div[3]/img</value>
      <webElementGuid>8a17ae3f-19c5-464e-a109-c0e031755c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cloud Application Development Services']</value>
      <webElementGuid>b75c1a84-0d47-476b-a237-706d2eb5ef1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/img</value>
      <webElementGuid>bc237783-c288-482d-a46b-f4e6b1aacb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Cloud Application Development Services' and @src = 'https://demo19xperience13.raybiztech.com/RBT/media/RBT-Images/bigstock-cloud-computing.jpg']</value>
      <webElementGuid>76e6057a-eef9-4550-a36a-79b3c7f41191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
