<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ARTIFICIAL INTELLIGENCE</name>
   <tag></tag>
   <elementGuidId>8e984458-abd6-438a-99f6-b91a57e3e302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.hidden-xs.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/header/div/div[2]/nav/div[4]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5343ea1a-ddbc-4912-96af-bcf00669b1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>07c5a1db-9c85-4f6b-a10c-6785722e4aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>82fb0c0f-aa41-43a4-900d-f9cb95dea860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>2121cf23-99cf-4e6a-aef4-0546cf7b1aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>425cd1ac-7eeb-440d-901a-cda15a55b4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>9adb57d4-32ab-4b39-bbdb-837191f8fc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>22863c02-1c03-466c-af76-6c3bca087573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>87656c92-511a-41e7-af60-d4b200706fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d2fb72d-d9cc-46c9-b565-214ea312a992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>6e360c25-d0fe-471d-8258-da9c4e6df9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>11c9df63-15e9-4380-ad4e-28c092a523f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>7a5ee7ca-a3e9-4168-86f1-9af3cad6881c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c5d29dc-6d58-4ab9-8c6b-631a0e9df24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>e5845f5d-3a44-41ac-8a8f-71f26e4db322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>df622aa0-8c83-4982-b561-48bf68372daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>7754b5c0-c503-4571-b0c7-324098431388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00d80950-9455-49a6-bdd2-32adf620ca32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>cdab515c-08a7-4c3e-a9b0-1c4952aff10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>3a04e9ea-9e17-4f7c-b2d7-12bb91c0773e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>360951a2-ec19-46dc-8809-672cbe018cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5648e0c4-4139-4ef9-9d5a-3e41f50251f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>64ae8855-934f-449c-b962-6fc029751c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>bf769a04-9d49-49c0-acb0-30309c01670b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>f0efc5c9-b28f-44a3-90c4-9423e9925a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08a71995-d58d-4480-adf0-2c5332c6cfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>00257081-ffd9-43b7-b2d9-94493ea7abfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>35ad88a1-bc87-4d1b-947f-400512454b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>647d84a0-880a-44b1-a1aa-01efd34e5d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25cbafcd-867e-420a-930c-93fa696692d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>a7fe7c57-5dd1-4e76-b740-2ede8e1c7f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>0d313c7a-5549-4e92-846b-48b4a1749ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>da0f611b-d5fd-4c5b-bc35-960558365de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e52c99b-a2ee-4b68-8d1a-7a709b61a099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>020ddee9-7340-4e5e-bca9-3b62a0a9cbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>7ea5b863-cbb8-4958-9bae-2e0bfac563ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>75cf2095-a8c9-4d41-b72b-2c1f97d1aee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4484914a-4cb9-4024-a3db-80597aa4066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence</value>
      <webElementGuid>39739aad-4da9-4fb9-936b-4857dd7b0584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ARTIFICIAL INTELLIGENCE</value>
      <webElementGuid>e5bc6fd9-dc35-482f-91e0-3616be1239ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>7105a3e7-1a6c-427b-9eed-838f6f68e73e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/header/div/div[2]/nav/div[4]/ul/li/a</value>
      <webElementGuid>98376e1e-aa01-4bfb-9cba-4262a5b342d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ARTIFICIAL INTELLIGENCE')]</value>
      <webElementGuid>017fb508-dabe-484e-865d-78b597a5e088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamics 365'])[1]/preceding::a[1]</value>
      <webElementGuid>0b2ee940-4c32-44ad-9275-1a3385b3876e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KENTICO XPERIENCE 13'])[1]/preceding::a[2]</value>
      <webElementGuid>c78099dc-d399-484e-a7ab-95def87b30d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ARTIFICIAL INTELLIGENCE']/parent::*</value>
      <webElementGuid>7d1b7309-5c98-4965-8a2b-66d3b415f3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/Solutions/Artificial-IntellIgence')]</value>
      <webElementGuid>3ca57ee5-22c6-410d-a3b1-40cf98c8847d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>86b0109f-269f-4a03-8c2f-283b47f3e925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/Solutions/Artificial-IntellIgence' and (text() = 'ARTIFICIAL INTELLIGENCE' or . = 'ARTIFICIAL INTELLIGENCE')]</value>
      <webElementGuid>d608217f-c572-4332-942b-ff74f14da6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence')]</value>
      <webElementGuid>0d5d9f85-2395-4f96-9c20-e8fa49142ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/Solutions/Artificial-IntellIgence' and (text() = 'ARTIFICIAL INTELLIGENCE' or . = 'ARTIFICIAL INTELLIGENCE')]</value>
      <webElementGuid>ce19d1e6-d784-49f9-ba72-d6f747872e8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
