<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_E-Commerce  Social Media</name>
   <tag></tag>
   <elementGuidId>2e359ae4-ff9d-43c6-8349-df8f1f7c495a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.time-placement-content-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='post']/div[2]/div/div/div/div/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>92ae9bdc-1975-4c06-ab77-c2421aa4b583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>time-placement-content-left</value>
      <webElementGuid>00864a76-b0e0-4ba7-9839-19d60e64bfff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-Commerce &amp; Social Media</value>
      <webElementGuid>1db4de7e-1aed-4a8f-a286-9eb95371a719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[@id=&quot;post&quot;]/main[@id=&quot;post&quot;]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;hdngtxt time-placement-content&quot;]/h1[@class=&quot;time-placement-content-left&quot;]</value>
      <webElementGuid>8430f600-b7e8-47f3-8da7-59cd21556fda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='post']/div[2]/div/div/div/div/div[2]/h1</value>
      <webElementGuid>b4b67279-943d-469b-b03d-2eec438c86cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Commerce &amp; Social'])[2]/following::h1[1]</value>
      <webElementGuid>e0fd862f-6cac-458c-8d50-2c67cab10d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solutions'])[1]/following::h1[1]</value>
      <webElementGuid>9e545016-c423-4a5c-9ba4-b69d7df1746b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online storefronts, catalogs and shopping carts'])[1]/preceding::h1[1]</value>
      <webElementGuid>0c02e8c3-dad6-426f-86c3-9b128ab9d641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web-based administration products for managing inventory, coupon codes and gift certificates'])[1]/preceding::h1[1]</value>
      <webElementGuid>bc0d75de-a5f3-4e1d-9978-6ba82caf32a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='E-Commerce &amp; Social Media']/parent::*</value>
      <webElementGuid>dc35d04d-606d-4141-8a5a-affb55ab6b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>8a69d1f8-dc85-4169-b740-7958718c9a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'E-Commerce &amp; Social Media' or . = 'E-Commerce &amp; Social Media')]</value>
      <webElementGuid>cb1fbd15-c5e0-4f99-88c3-bbf69653aa38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
