<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Its a fact to believe that a quantum ERP _a03536</name>
   <tag></tag>
   <elementGuidId>5dea9509-3db5-4f96-87c5-0c88a00f8779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='post']/div[2]/div/div/div/div/div[3]/p[22]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>857df342-43b4-431d-a4ff-ae8d5c61977f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>It’s a fact to believe that a quantum ERP can pledge to diminish your organization's administrative, operational and miscellaneous expenses by 45%. It federates your fragmented systems for creating a cost-efficient business processes. As all the users will be trained using a single system, you’ll be cutting the associated costs while adding capital appreciation in your annual balance sheets.</value>
      <webElementGuid>9022f309-151b-4669-bb81-5ffc94c9fd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[@id=&quot;post&quot;]/main[@id=&quot;post&quot;]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;inrtxt&quot;]/p[22]</value>
      <webElementGuid>b57f00c8-3693-4f87-a2ad-10ede4f8feb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='post']/div[2]/div/div/div/div/div[3]/p[22]</value>
      <webElementGuid>39a16a94-dbd3-4500-a985-e47e52d79b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-budget ERP for Cost Crunching'])[1]/following::p[1]</value>
      <webElementGuid>ace24073-b6cb-4ac7-aab8-bc014dcce749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross-functional Collaboration for Transparent Results'])[1]/preceding::p[1]</value>
      <webElementGuid>e51af873-0e6a-46b9-a7c7-4bdd73dc93f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web-based ERP Favors IoT Devices for Mobility'])[1]/preceding::p[2]</value>
      <webElementGuid>e5e8f0e5-1213-4679-a989-085afca5d157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[22]</value>
      <webElementGuid>08ffd0d5-5124-45bf-8731-5f5a3ef8ab18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;It’s a fact to believe that a quantum ERP can pledge to diminish your organization&quot; , &quot;'&quot; , &quot;s administrative, operational and miscellaneous expenses by 45%. It federates your fragmented systems for creating a cost-efficient business processes. As all the users will be trained using a single system, you’ll be cutting the associated costs while adding capital appreciation in your annual balance sheets.&quot;) or . = concat(&quot;It’s a fact to believe that a quantum ERP can pledge to diminish your organization&quot; , &quot;'&quot; , &quot;s administrative, operational and miscellaneous expenses by 45%. It federates your fragmented systems for creating a cost-efficient business processes. As all the users will be trained using a single system, you’ll be cutting the associated costs while adding capital appreciation in your annual balance sheets.&quot;))]</value>
      <webElementGuid>4466f577-6e33-4ab6-9478-0960a48ccb48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
