<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Powerful ERP solutions are rolled up with_d40ef8</name>
   <tag></tag>
   <elementGuidId>305e7348-4d7c-4926-98ec-6e10bff44264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='post']/div[2]/div/div/div/div/div[3]/p[28]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>07a7c6e4-ac3b-4bde-b27c-a178a4104bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Powerful ERP solutions are rolled up with the regulatory compliance of any organization for keeping track of the regulations within the industry while monitoring the amendments every now and then.  </value>
      <webElementGuid>9ae8c0c1-a85d-4678-8272-f9937e327cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[@id=&quot;post&quot;]/main[@id=&quot;post&quot;]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;inrtxt&quot;]/p[28]</value>
      <webElementGuid>da1c1d0f-21e8-4170-bd71-7d3cb7c6ae21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='post']/div[2]/div/div/div/div/div[3]/p[28]</value>
      <webElementGuid>606c08d0-2242-4991-b293-ae88c1f65b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Off-the-Ground ERP for Regulatory Compliance'])[1]/following::p[1]</value>
      <webElementGuid>ff0500a2-8ed8-4307-b237-6c65be9ab542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Protection &amp; Information Privacy'])[1]/preceding::p[1]</value>
      <webElementGuid>eadaf397-41c6-41f7-a6d2-4376b8d22ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[28]</value>
      <webElementGuid>d840063f-463b-4e33-86a4-4422d38abcb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Powerful ERP solutions are rolled up with the regulatory compliance of any organization for keeping track of the regulations within the industry while monitoring the amendments every now and then.  ' or . = 'Powerful ERP solutions are rolled up with the regulatory compliance of any organization for keeping track of the regulations within the industry while monitoring the amendments every now and then.  ')]</value>
      <webElementGuid>d2acaed7-d49e-49ef-8f73-de2a977e3d3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
