<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Enterprise Portal  Content Management</name>
   <tag></tag>
   <elementGuidId>725e22b6-5fc1-4592-839a-3055cb7926c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.time-placement-content-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div[2]/div/div/div/div/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0baf4e43-ea1e-4caf-a3f7-bac9ef865140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>time-placement-content-left</value>
      <webElementGuid>449307fb-91e6-46b1-a59a-c39ee21870fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enterprise Portal &amp; Content Management</value>
      <webElementGuid>d7e67ebf-c9dc-43a1-a2cc-836c3c09a41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;hdngtxt time-placement-content&quot;]/h1[@class=&quot;time-placement-content-left&quot;]</value>
      <webElementGuid>2946f3e2-66e0-4536-b9eb-8c9eedecf51a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div[2]/div/div/div/div/div[2]/h1</value>
      <webElementGuid>8ccd838d-5426-4cbc-9b0c-f952d03a6662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Portal &amp; Content Management'])[2]/following::h1[1]</value>
      <webElementGuid>c9b176af-1972-439c-9d75-2e349e52d255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solutions'])[1]/following::h1[1]</value>
      <webElementGuid>8ec55355-6d68-4394-ad37-15eb24418d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Difficulty in finding the right information at the right time'])[1]/preceding::h1[1]</value>
      <webElementGuid>8d5cd22e-6834-4477-955f-bbb64efa9dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trouble to make sense of content dispersed across many Internet an intranet portals'])[1]/preceding::h1[1]</value>
      <webElementGuid>57fe68b1-d4e0-4099-9a81-61f1880f0e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>8b92902f-b125-40e2-9440-22aea94abfe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Enterprise Portal &amp; Content Management' or . = 'Enterprise Portal &amp; Content Management')]</value>
      <webElementGuid>42b644ed-db2b-4e98-8321-0c89270f88c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
