<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Enterprise Portal  Content Management_i_31a827</name>
   <tag></tag>
   <elementGuidId>95c4b45b-a175-4362-9045-4e36162c0100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.inner-img-right.col-lg-6.col-md-6.center-block.img-responsive.pull-right.xs-float-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div[2]/div/div/div/div/div[3]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66857af5-7efb-418a-80c8-f5499cc9c3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inner-img-right col-lg-6 col-md-6 center-block img-responsive pull-right xs-float-none</value>
      <webElementGuid>3eb582f1-e4a5-4e56-8c3b-d4e9d3c9ca1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/Enterprise-Portal-Content-Management.jpg</value>
      <webElementGuid>ea983e79-5f1e-4077-9b82-5f39b8fa926e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;inrtxt imxtxt&quot;]/div[@class=&quot;imageGallery&quot;]/a[1]/img[@class=&quot;inner-img-right col-lg-6 col-md-6 center-block img-responsive pull-right xs-float-none&quot;]</value>
      <webElementGuid>3785513c-fe77-4560-ba58-c1172ab016b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div[2]/div/div/div/div/div[3]/div/a/img</value>
      <webElementGuid>6990d0de-ed53-4eab-880c-1201318104b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/Enterprise-Portal-Content-Management.jpg')]</value>
      <webElementGuid>d8517083-d238-417b-865f-a8e18de972cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img</value>
      <webElementGuid>ae9ed9a0-558b-4435-8ece-d06a536f6c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/Enterprise-Portal-Content-Management.jpg']</value>
      <webElementGuid>e817213a-c3e5-4c53-bc0e-f5cc986b2d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
