<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Digital Signage</name>
   <tag></tag>
   <elementGuidId>c2df16f2-b728-4e17-9d6e-46fd27e98771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div[2]/div/div/div/div/div[3]/ul[4]/li[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0a18500c-62bf-4813-a4a6-8ae3205e67ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Digital Signage</value>
      <webElementGuid>e951b711-7492-401a-991e-a3c19f02fb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;inrtxt imxtxt&quot;]/ul[4]/li[10]</value>
      <webElementGuid>5871ac07-b46a-421f-8274-be6eead12411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div[2]/div/div/div/div/div[3]/ul[4]/li[10]</value>
      <webElementGuid>9142eea1-b83a-4825-ace5-19f8eac3496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content Migration'])[1]/following::li[1]</value>
      <webElementGuid>1e6c10b8-f8cf-4f9c-a847-da4aa18222ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liferay Portal Solutions'])[1]/following::li[2]</value>
      <webElementGuid>124a7dcc-6eed-41d2-b19a-f91c0d078be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Related'])[1]/preceding::li[1]</value>
      <webElementGuid>014aaddf-defa-4d58-87cf-036a4db65aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li[10]</value>
      <webElementGuid>dc584009-f6af-4f8b-9ea1-8b677e283943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Digital Signage' or . = 'Digital Signage')]</value>
      <webElementGuid>5def5237-0834-47be-ab35-8422478c704a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
