<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View all</name>
   <tag></tag>
   <elementGuidId>5b646437-720a-42d2-a228-63769a2d02fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-center.custom-button.btn-transparent-primary.btn-large.mart-35.videoscroll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div/section[4]/div[2]/div/div/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d0d5ebe-6321-4337-9420-30f2530b0140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/CategoryVideos?catID=PLtmHTlSHwoYqaVNxA54t5ZxZSF-bXe0Lv&amp;pgTle=Boomi-Services%20and%20Solutions%20Videos&amp;uh=867d4dca288a9d0e2ee6f361a1fad139e6a0d27aa582aea04c723b09cfd6d3f9</value>
      <webElementGuid>46c73c93-d407-4819-8ecc-febf430050d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center custom-button btn-transparent-primary btn-large mart-35 videoscroll</value>
      <webElementGuid>e3fdee4e-197b-4414-8f35-97a4acb29c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View all</value>
      <webElementGuid>55c43a5d-108b-4636-ad99-d3b0c7351e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;services dell_boomi&quot;]/section[@class=&quot;sec-pad&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;clearfix mrg-lr&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;text-center custom-button btn-transparent-primary btn-large mart-35 videoscroll&quot;]</value>
      <webElementGuid>43ce904f-a60e-48e1-b4a0-5add2d0a923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>221a3e7d-53a9-4875-b44d-43ee23fcacee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/CategoryVideos?catID=PLtmHTlSHwoYqaVNxA54t5ZxZSF-bXe0Lv&amp;pgTle=Boomi-Services%20and%20Solutions%20Videos&amp;uh=867d4dca288a9d0e2ee6f361a1fad139e6a0d27aa582aea04c723b09cfd6d3f9</value>
      <webElementGuid>a07bf246-e1d9-46b9-88df-b732e9749160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center custom-button btn-transparent-primary btn-large mart-35 videoscroll</value>
      <webElementGuid>9bf1f346-825a-4e01-80cc-232f9f86a42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View all</value>
      <webElementGuid>d541caf4-545a-477b-8aff-1a6e10562e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;services dell_boomi&quot;]/section[@class=&quot;sec-pad&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;clearfix mrg-lr&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;text-center custom-button btn-transparent-primary btn-large mart-35 videoscroll&quot;]</value>
      <webElementGuid>439f2d4d-b478-4a21-a5b5-35c737592f19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div/section[4]/div[2]/div/div/div/div[3]/a</value>
      <webElementGuid>e9689bab-61a1-42c7-bfe1-825e79621530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View all')]</value>
      <webElementGuid>9185a350-9be3-400e-8b0c-35404cdc6f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Boomi is important to your Business? | Ray Business Technologies'])[1]/following::a[1]</value>
      <webElementGuid>fe9b87e1-0af2-4c7b-99fe-cee74dd03566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boomi for Healthcare | Ray Business Technologies'])[1]/following::a[3]</value>
      <webElementGuid>6db5f52f-633e-4071-8b10-5abce525340d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct WhatsApp Chat'])[1]/preceding::a[1]</value>
      <webElementGuid>1d1c07df-ef66-4606-8f5d-030d24eb127f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Quote'])[2]/preceding::a[2]</value>
      <webElementGuid>06ca776d-3cc8-4388-ad04-f878da65d457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View all']/parent::*</value>
      <webElementGuid>aaae3cac-03ba-4cd2-9d26-c17e6f5d1262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/CategoryVideos?catID=PLtmHTlSHwoYqaVNxA54t5ZxZSF-bXe0Lv&amp;pgTle=Boomi-Services%20and%20Solutions%20Videos&amp;uh=867d4dca288a9d0e2ee6f361a1fad139e6a0d27aa582aea04c723b09cfd6d3f9')]</value>
      <webElementGuid>18b285b5-1f9b-4f03-ba03-cbefe9e14a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/a</value>
      <webElementGuid>db7250c3-de4f-4fb6-bf81-f3e2f2a50ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/CategoryVideos?catID=PLtmHTlSHwoYqaVNxA54t5ZxZSF-bXe0Lv&amp;pgTle=Boomi-Services%20and%20Solutions%20Videos&amp;uh=867d4dca288a9d0e2ee6f361a1fad139e6a0d27aa582aea04c723b09cfd6d3f9' and (text() = 'View all' or . = 'View all')]</value>
      <webElementGuid>23649bea-b3e5-4b4b-a97a-ecac8fdfc430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
