<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_BOOMI - EAI</name>
   <tag></tag>
   <elementGuidId>a613d8c8-f8bf-49c1-80a5-b8491af4327f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.banner_heading2.hidden-xs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div/div/section/div[2]/div/div/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e6692a34-351f-4b83-af83-8cb1a45fc6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner_heading2 hidden-xs</value>
      <webElementGuid>29ab4cc4-f15b-474f-9e49-d35d2ddf0ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOOMI - EAI</value>
      <webElementGuid>85583c23-b576-4aee-b66d-aa95a784d715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;services dell_boomi&quot;]/div[1]/section[@class=&quot;page-banner clouds&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;center&quot;]/div[@class=&quot;row center-item col_2&quot;]/div[@class=&quot;col-md-4 col-md-pull-8 pl-banner col_2_right_side&quot;]/h1[@class=&quot;banner_heading2 hidden-xs&quot;]</value>
      <webElementGuid>927f39ac-b3b5-45c8-b72c-4840bf72b6cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div/div/section/div[2]/div/div/div[2]/h1</value>
      <webElementGuid>95385427-6818-4e68-b14d-12bfb99d312c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOOMI - EAI'])[4]/following::h1[1]</value>
      <webElementGuid>2beb03e0-7891-4835-91bc-a8458ef149f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::h1[1]</value>
      <webElementGuid>823aefc3-c67c-424f-85ec-3bb41876bfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOOMI SERVICES &amp; SOLUTIONS'])[1]/preceding::h1[1]</value>
      <webElementGuid>0baba70e-95db-4fca-9c59-b90aa949549a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h1</value>
      <webElementGuid>6ff14d7f-e2d3-4664-ab9a-f8c419ab65e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'BOOMI - EAI' or . = 'BOOMI - EAI')]</value>
      <webElementGuid>8c8c1faf-636f-4ab4-bec7-db359d69fe53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
