<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>d3f76492-0392-49d7-96e7-4f983dc0b38b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ol.breadcrumb.hidden-xs > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/section[2]/div/ol/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec4f8c39-e5c9-47c9-bd40-dc7c72d5e8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/</value>
      <webElementGuid>75657e10-e065-4c88-ad43-0d8d2a85b503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>f01f8696-6093-4901-9043-48591b6667b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/section[2]/div[@class=&quot;container&quot;]/ol[@class=&quot;breadcrumb hidden-xs&quot;]/li[1]/a[1]</value>
      <webElementGuid>7bd5d3e0-f4c5-4892-99b8-58a4dbfcab71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/section[2]/div/ol/li/a</value>
      <webElementGuid>64b525cc-7390-41f3-9a89-9d966c9f0b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home')]</value>
      <webElementGuid>dfb82f33-e53c-4174-9920-a81dcd782549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boomi - EAI'])[1]/following::a[1]</value>
      <webElementGuid>675b6951-0995-4144-ad9c-286589fcc12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Services'])[1]/following::a[2]</value>
      <webElementGuid>6d6d7f5c-a7c6-4af5-b38e-39f97e6dbca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solutions'])[1]/preceding::a[1]</value>
      <webElementGuid>6194ceb9-0a57-4078-a06b-c3f0f5e6b4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Science'])[2]/preceding::a[2]</value>
      <webElementGuid>add7d2fa-5fe7-4a54-8e7e-dc1cf44f42f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>8ce97732-33a0-414c-804e-f9d7573bd56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://demo3xperience13.raybiztech.com/')])[165]</value>
      <webElementGuid>c3cadbea-b0f9-4415-9b77-7afafae3a9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>eec21e7f-d793-4cef-8a3f-7b48ad47c5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/' and (text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>22e76233-2888-42dd-aed1-2ead12467cab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
