<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Data Science_center img-responsive</name>
   <tag></tag>
   <elementGuidId>f935c8ab-9c08-4997-acc4-2792c11a26f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.center.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div[2]/div/div/div/div/div[3]/div/div/div/section/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>00f2a837-c4ff-4d58-9f45-8c525518b9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>center img-responsive</value>
      <webElementGuid>01b09285-caea-4fce-9b26-7e0e54ced088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/data_science.png</value>
      <webElementGuid>5cd6ce9f-f6ea-4284-b27c-16bc5fc248c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;inrtxt imxtxt&quot;]/div[@class=&quot;main-widget ax_main&quot;]/div[@class=&quot;col-sm-12 pad0&quot;]/div[@class=&quot;row&quot;]/section[@class=&quot;widget-1 clearfix drupal-cms-main&quot;]/div[@class=&quot;col-sm-4 col-sm-push-8&quot;]/img[@class=&quot;center img-responsive&quot;]</value>
      <webElementGuid>0afb9d29-db5f-4549-930f-76b460c09aeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div[2]/div/div/div/div/div[3]/div/div/div/section/div/img</value>
      <webElementGuid>b93c3394-b592-4860-bc02-1402c860bdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/data_science.png')]</value>
      <webElementGuid>10f631a7-3c00-40fa-b57a-2bc697e76a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/img</value>
      <webElementGuid>4da653a7-0daa-406b-a832-3c20a84ee0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/data_science.png']</value>
      <webElementGuid>9a6e7cd9-5347-42f2-b7b1-3d7611b1c28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
