<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RESOURCES(current)</name>
   <tag></tag>
   <elementGuidId>bffc304a-17cd-4d9b-85c1-ab904faa5ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.sidebar_nav_item.active > a.sidebar_nav_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='megamenu']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6483f5f6-5f39-44fc-9985-cae819f1f35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>5c57d168-9d94-4d03-b931-858b807a3ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar_nav_link</value>
      <webElementGuid>8f33b13c-4f57-4617-b3c9-71dbe05f7628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                RESOURCES(current)
                                                            </value>
      <webElementGuid>41b5681a-baf1-42fb-a399-bddb88abd77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;megamenu&quot;)/ul[@class=&quot;sidebar_nav&quot;]/li[@class=&quot;sidebar_nav_item active&quot;]/a[@class=&quot;sidebar_nav_link&quot;]</value>
      <webElementGuid>db9d2fad-fced-4c49-ad19-ef0d71c3dcf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='megamenu']/ul/li[2]/a</value>
      <webElementGuid>f1beb2fa-5483-443c-9b9f-05151ef187c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOOMI - EAI'])[2]/following::a[1]</value>
      <webElementGuid>4daeea09-4695-465a-9629-9ee36a0f9733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Transformation'])[1]/following::a[2]</value>
      <webElementGuid>19f53010-44f7-41e1-b11a-aeaf1788bda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASE STUDIES'])[1]/preceding::a[1]</value>
      <webElementGuid>a80636b9-7eb2-4fbb-8336-ac53a7c8a9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RESOURCES']/parent::*</value>
      <webElementGuid>9b1deaae-c293-413f-b96c-2c6683b9ab32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>8e65bec6-28c9-410a-9e3c-8b268a7775bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>2bf4e7d7-120d-48d8-9589-81593963d71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = '
                                                                RESOURCES(current)
                                                            ' or . = '
                                                                RESOURCES(current)
                                                            ')]</value>
      <webElementGuid>944509d8-8dcc-457f-91aa-beefc62dbb47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
