<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ARTIFICIAL INTELLIGENCE_js_main-menu-icon</name>
   <tag></tag>
   <elementGuidId>583f1be5-3116-44a4-9628-3a47ee21c842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js_main-menu-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js_main-menu-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a78c545f-fc2c-4753-b79a-85a2a2a273b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b875747b-f3da-4dcc-a9ba-08322d31d634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>b994ac56-5853-4d41-b941-5f1301e08cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>438e3aa1-6c21-4136-9df0-caf328e3fe8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>main menu icon</value>
      <webElementGuid>f5453733-f5b9-4ee6-aa02-f4042137a0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js_main-menu-icon</value>
      <webElementGuid>e0454534-af49-4802-adde-a572a918cc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_main-menu-icon&quot;)</value>
      <webElementGuid>7dce187b-01d8-432c-8596-ba885907f231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js_main-menu-icon']</value>
      <webElementGuid>a8708a3e-0d97-4255-a897-45854031d075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/header/div/div[2]/nav/div[2]/button</value>
      <webElementGuid>c42d5868-f800-418e-99c5-5628b59ec122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARTIFICIAL INTELLIGENCE'])[1]/preceding::button[1]</value>
      <webElementGuid>9db3a58e-1e9b-4e26-b7a7-5bddb23d81e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamics 365'])[1]/preceding::button[1]</value>
      <webElementGuid>e0d02394-ebbe-452e-bfa1-48db3e5c18d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1f9eee07-333d-42eb-8c26-10250f90589a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'js_main-menu-icon']</value>
      <webElementGuid>1f59e471-138e-4156-ac1a-e1bfbd811c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
