<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KENTICO XPERIENCE 13</name>
   <tag></tag>
   <elementGuidId>4d29dc5d-a1be-4d71-87fa-62c075432229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/header/div/div[2]/nav/div[4]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>176752b9-b145-4d7b-ad57-2e0d53177c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/epcm/Kentico-Xperience-13</value>
      <webElementGuid>f8cf9e16-cfb6-449a-b62b-2c42a32148ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KENTICO XPERIENCE 13</value>
      <webElementGuid>1d0d9524-fd43-401b-9f23-dc2e2a94dff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>b72a4d6d-31b0-41da-b663-911d4a39b093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3412690c-c83f-4ef9-be85-eeb587175561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/Solutions/epcm/Kentico-Xperience-13</value>
      <webElementGuid>47c7730c-e9f4-4fb1-a044-49bbe430a25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KENTICO XPERIENCE 13</value>
      <webElementGuid>02280ffc-61b3-4ce4-ac60-8bc18fdf4068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/header[1]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;navbar navbar-default&quot;]/div[@class=&quot;collapse navbar-collapse navbar-right&quot;]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[@class=&quot;hidden-xs active&quot;]/a[1]</value>
      <webElementGuid>a867b5d2-6af2-48e0-9e53-689e04981e42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/header/div/div[2]/nav/div[4]/ul/li[3]/a</value>
      <webElementGuid>7e335d85-e441-4ee7-9bf6-981963a0af5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KENTICO XPERIENCE 13')]</value>
      <webElementGuid>bfae93a4-6ecf-44d0-981c-e69d9e2bba35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamics 365'])[1]/following::a[1]</value>
      <webElementGuid>01cb763d-e329-4d3a-80b7-f44f682a065a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARTIFICIAL INTELLIGENCE'])[1]/following::a[2]</value>
      <webElementGuid>9f20d65e-9aff-4af4-9bed-ff43ec579762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAREERS'])[1]/preceding::a[1]</value>
      <webElementGuid>43b63837-bc9a-4a96-81c9-b8834f65fa85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT'])[1]/preceding::a[2]</value>
      <webElementGuid>b8a3c822-2e72-468f-a8e4-7279b4797ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KENTICO XPERIENCE 13']/parent::*</value>
      <webElementGuid>65461fd6-df99-456b-b33c-fb8208a46d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/Solutions/epcm/Kentico-Xperience-13')]</value>
      <webElementGuid>df9b4b60-7a1b-43f0-9be9-b3f898dbba94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>3959f1ba-cb0b-4e95-85ef-05a988bbbc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/Solutions/epcm/Kentico-Xperience-13' and (text() = 'KENTICO XPERIENCE 13' or . = 'KENTICO XPERIENCE 13')]</value>
      <webElementGuid>de655778-26f1-497d-a292-2629fead89a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
