<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Exciting journey. We plan your progress_3767d0</name>
   <tag></tag>
   <elementGuidId>f5a8a69b-1554-42b5-8f7a-30c2ec1c437b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/section/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.banner-text-display > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7d6e43e1-2808-4295-97ca-fd42a82aa09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Careers</value>
      <webElementGuid>d05fb1e0-1f3f-4a76-a1ee-334ec841bc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/career-bg-2.png?ext=.png</value>
      <webElementGuid>6b199c94-96ac-47a8-8885-b400c7532a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>f3559580-062d-4a18-be6a-dc332297ddd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/section[@class=&quot;inner-banner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;banner-text row&quot;]/div[@class=&quot;col-sm-6 banner-text-display&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>4e92a96a-f540-4910-b19e-9cba5268ecaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/section/div/div/div[2]/img</value>
      <webElementGuid>131bd2fd-6030-4c43-85b7-c71b5b6400cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Careers']</value>
      <webElementGuid>ab384f2f-c434-441e-9b4c-aa789f86b810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/img</value>
      <webElementGuid>0421ac2b-fc7c-49da-a05a-317a66bec85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Careers' and @src = 'https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/career-bg-2.png?ext=.png']</value>
      <webElementGuid>a5aac9b7-d807-485b-9c13-db1b95dbfb0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
