<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Technical Skills</name>
   <tag></tag>
   <elementGuidId>db61764c-0ff8-46fe-87c5-99771a978eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='4']/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>05d1ec77-4fe5-4d13-8023-17747c16b27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Technical Skills:</value>
      <webElementGuid>5e5f5e3c-fa07-4aa4-b548-fdfb7c432d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)/div[@class=&quot;panel-body circle-dot black-dot&quot;]/p[2]</value>
      <webElementGuid>77926d2c-14fd-4172-b09f-bc576b5c3a97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/p[2]</value>
      <webElementGuid>159a0a92-c5a3-4e5b-9d38-60cd84a51a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show More...'])[3]/following::p[1]</value>
      <webElementGuid>be014756-97f2-4b92-8798-5f8fb02c7e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good communication, analytical presentation skills, problem solving skills and learning attitude'])[1]/following::p[1]</value>
      <webElementGuid>36284029-7ece-454d-ba6c-45d723c61cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C#'])[1]/preceding::p[1]</value>
      <webElementGuid>70d14a41-b65b-4ad3-a8e0-cf6e58b2583b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div[4]/div[2]/div/p[2]</value>
      <webElementGuid>96460e13-df92-4a5b-a30a-fd669f190a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Technical Skills:' or . = 'Technical Skills:')]</value>
      <webElementGuid>e36e21e6-53c6-45b2-8cd0-7f375600ad8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
