<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Experience  8 years</name>
   <tag></tag>
   <elementGuidId>79bf7919-8a08-4aec-8269-2187ce21cb57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='headingOne']/h4/small)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>630855ae-77d8-4bd1-953e-efa218f67fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Experience:  8+ years  </value>
      <webElementGuid>68505a6a-2564-4051-95cd-71246f4bf8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@id=&quot;headingOne&quot;]/h4[1]/small[1]</value>
      <webElementGuid>8c0f5cbd-a1bc-433f-b3f3-c18b0cb5d704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='headingOne']/h4/small)[3]</value>
      <webElementGuid>a474de94-6d73-419c-81a3-2663aef6158c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='careers@raybiztech.com'])[2]/following::small[1]</value>
      <webElementGuid>30e4baed-f22a-46f8-8935-055469db9f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location - Hyderabad, India &amp; Philippines'])[2]/preceding::small[1]</value>
      <webElementGuid>7049e7ae-63ed-4b6b-9427-e858d9a9e03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h4/small</value>
      <webElementGuid>9f94ac4a-bab2-4504-8b31-e00e1a469033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Experience:  8+ years  ' or . = 'Experience:  8+ years  ')]</value>
      <webElementGuid>bfa78305-176e-4103-a71a-a6711605061e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
