<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Key Skills</name>
   <tag></tag>
   <elementGuidId>fdaaa630-6a23-4e4b-8134-53c4b6b83c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='4']/div/p/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>7de82bcd-b9d1-4040-966a-3258f7c61fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Key Skills:</value>
      <webElementGuid>039d3474-75eb-4d2d-ae17-d9fc724586b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)/div[@class=&quot;panel-body circle-dot black-dot&quot;]/p[1]/strong[1]</value>
      <webElementGuid>0655ce4d-18f5-477b-8f7b-ad9437e9fc32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div/p/strong</value>
      <webElementGuid>b9238a22-1542-4a7d-895b-01cb21768352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experienced in Architecture Design, Solution Design, Technical consulting and Pre-Sales activities'])[1]/preceding::strong[1]</value>
      <webElementGuid>18eac755-ef17-4b18-b176-026d19cb7398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Key Skills:']/parent::*</value>
      <webElementGuid>558ee48b-4b6b-407c-9e53-8bfe955e544c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>41799436-bcae-47c2-b442-c97fb76ab7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Key Skills:' or . = 'Key Skills:')]</value>
      <webElementGuid>f3fd8d2f-cec9-4eee-9eea-ac4d4cd6c1b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
