<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Boomi - EAI</name>
   <tag></tag>
   <elementGuidId>14d10fbc-33f5-4654-b4a6-f088a5389877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0cd7043-d6f2-49c2-933e-b8bc96c5cf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/Dell-Boomi-ServicesandSolutions</value>
      <webElementGuid>9bdb15e2-d5f3-4ada-bac7-e606a9ff790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Boomi - EAI</value>
      <webElementGuid>a1dc4d68-0b8f-4266-98a2-ab5ba71f49d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/li[4]/a[1]</value>
      <webElementGuid>33ff6525-f83f-4bfe-ba32-97d1e597c702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54c11771-7145-46d5-9af9-dc754eae21a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/Dell-Boomi-ServicesandSolutions</value>
      <webElementGuid>bf93176c-964e-4695-ba37-0a1df919e764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Boomi - EAI</value>
      <webElementGuid>bed1c6cd-00be-4607-bfe9-bf3099a5bf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/li[4]/a[1]</value>
      <webElementGuid>79846ab2-3af9-403d-86f9-3c7feb3106a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/li[4]/a</value>
      <webElementGuid>462efcb4-7d29-4c1e-9f53-f012f1a4d4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Boomi - EAI')]</value>
      <webElementGuid>07b532bb-cf34-49ea-ba48-e5651951afac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Services'])[1]/following::a[1]</value>
      <webElementGuid>5a2e7cd7-0425-4b9c-a742-d99c5b90323b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artificial Intelligence'])[1]/following::a[2]</value>
      <webElementGuid>da00420c-6d5a-4c57-ae8c-6a6fa929ecf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[1]</value>
      <webElementGuid>365aaf21-86f3-4cb3-89cb-538bdb4ba3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solutions'])[1]/preceding::a[2]</value>
      <webElementGuid>abe08988-cb55-43a7-903f-8fa2e6cb2b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Boomi - EAI']/parent::*</value>
      <webElementGuid>7b20ba8a-8141-465a-acda-7c048b0217ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://demo19xperience13.raybiztech.com/solutions/Dell-Boomi-ServicesandSolutions')])[4]</value>
      <webElementGuid>fd753d6f-d88a-4fab-9fec-0e8f686c08a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[4]/a</value>
      <webElementGuid>3676ea90-c1ce-46be-bffb-a3ce919e4f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/solutions/Dell-Boomi-ServicesandSolutions' and (text() = 'Boomi - EAI' or . = 'Boomi - EAI')]</value>
      <webElementGuid>b837c255-dde7-4364-8aaf-7c60812335b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
