<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cloud Services</name>
   <tag></tag>
   <elementGuidId>473833a4-3574-404a-84dc-efc902624568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cb9397e-6b5b-498f-a462-2db05cb861bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/Cloud-Services</value>
      <webElementGuid>c0e27eeb-3317-45c9-b3df-f9310cb7fc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cloud Services</value>
      <webElementGuid>23cc462f-a325-43e6-aa09-fef8f327e4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/li[3]/a[1]</value>
      <webElementGuid>e4eab1ec-7b27-48be-8e3f-01f222daef7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/li[3]/a</value>
      <webElementGuid>77972b16-5c21-4d1a-b58a-7e286e94dbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cloud Services')]</value>
      <webElementGuid>fce40a10-96b0-409e-b706-3164b3d397e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artificial Intelligence'])[1]/following::a[1]</value>
      <webElementGuid>d7d46b89-8e5a-48ec-a5ae-58a66acf23a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Science'])[1]/following::a[2]</value>
      <webElementGuid>c22869b1-c66a-4fdd-a3e6-e306f1a59c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boomi - EAI'])[1]/preceding::a[1]</value>
      <webElementGuid>ca41e596-d5eb-4aa3-9712-ee5b63464d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[2]</value>
      <webElementGuid>8aabdb63-af08-4b26-a6a3-670c4cb3f2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cloud Services']/parent::*</value>
      <webElementGuid>dc9953c5-2c85-448e-9e9d-2b83abcdd58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/solutions/Cloud-Services')]</value>
      <webElementGuid>fa043ad3-5d9b-46ff-9fb1-bc3cb93a0142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[3]/a</value>
      <webElementGuid>c58853fe-08f8-47f8-bb8c-a4dbec5f2e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/solutions/Cloud-Services' and (text() = 'Cloud Services' or . = 'Cloud Services')]</value>
      <webElementGuid>0d91fa7e-a9b7-4925-b662-a8261a772698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
