<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enterprise Resource Planning</name>
   <tag></tag>
   <elementGuidId>38daa8bf-101a-4582-88ac-9acef519734a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.visible-links > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div/div/nav/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa701021-6adf-4239-ba4a-72e682633e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/solutions/Enterprise-Resource-Planning</value>
      <webElementGuid>b3e9c659-9442-4a30-93c2-664c3be477eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enterprise Resource Planning</value>
      <webElementGuid>bc603afb-49cb-44e5-8c9a-990411e10f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;gradient-bg_2&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;greedy-nav&quot;]/ul[@class=&quot;visible-links&quot;]/li[1]/a[1]</value>
      <webElementGuid>d4c988c5-23a5-460a-b429-db41656dc2dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div/div/nav/ul/li/a</value>
      <webElementGuid>6c76f4dc-5d83-4bc6-bf6e-1e8550022e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enterprise Resource Planning')]</value>
      <webElementGuid>f3364583-4f4c-46d4-8822-5876c16a4857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology + People + Process'])[1]/following::a[1]</value>
      <webElementGuid>3de21c0b-477b-43a3-b5ce-d473200e11eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Portal &amp; Content Management'])[1]/preceding::a[1]</value>
      <webElementGuid>02d91549-61fb-4777-a8b3-cf8bc5cdfc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Commerce &amp; Social'])[1]/preceding::a[2]</value>
      <webElementGuid>8201acac-e872-4a76-aadf-009ce151513c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enterprise Resource Planning']/parent::*</value>
      <webElementGuid>62d74a68-a50c-45a8-8e38-d14f27b32c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/solutions/Enterprise-Resource-Planning')]</value>
      <webElementGuid>60f107ef-4c32-4a2e-a4d5-c885d8ce0fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/nav/ul/li/a</value>
      <webElementGuid>469a4956-9e92-4e03-84f2-58279b94aa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/solutions/Enterprise-Resource-Planning' and (text() = 'Enterprise Resource Planning' or . = 'Enterprise Resource Planning')]</value>
      <webElementGuid>2c843eb3-2e50-48c4-99ef-6aa07450fe1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
