<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Technology  People  Process_hamburger</name>
   <tag></tag>
   <elementGuidId>f0d9463f-e357-4809-99ed-df30b768566a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.hamburger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div/div/nav/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>336566b1-1050-4c04-a08c-38efe95a9581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburger</value>
      <webElementGuid>095913f7-ec82-4bae-9347-bfad08185fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;gradient-bg_2&quot;]/div[@class=&quot;container&quot;]/nav[@class=&quot;greedy-nav&quot;]/button[1]/div[@class=&quot;hamburger&quot;]</value>
      <webElementGuid>0ed898de-cf70-4878-adc7-46cf0024f11c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div/div/nav/button/div</value>
      <webElementGuid>221bfa42-ffeb-410c-82f7-862eb9a4ed0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>44d9fd06-7668-4d3e-9220-d20346248bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
