<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dynamics NAV Filled with Dosage of Discounts</name>
   <tag></tag>
   <elementGuidId>6c1fc6d6-646c-453d-8b7b-14aa60989108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='248']/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36b9d5a3-99bf-43a0-b080-4d34f49578e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse248</value>
      <webElementGuid>314eeb07-75e2-406b-ab2c-d2aa11da5b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ee3c994-9129-46ac-9ca3-041cfba0652e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>d735fa50-7b89-4a50-a46e-9f37e03fa611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>26d75c3b-e1b9-4649-adf1-f969a8ec53d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>559aca4c-aa75-4d13-8569-cf2a6bf4fa11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-nav-solutions#collapse248</value>
      <webElementGuid>b74aa8e6-d989-4e90-b064-25625c917426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fcd205a7-5d4b-44ed-90f2-746ceb26175e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dynamics NAV Filled with Dosage of Discounts </value>
      <webElementGuid>d588a4c5-25bb-4800-8053-dc64a24c7b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;248&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>4e43703a-6c67-4530-914d-2daed24fdf76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='248']/h4/a</value>
      <webElementGuid>199a119a-3431-4257-94b4-38510804e5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dynamics NAV Filled with Dosage of Discounts')]</value>
      <webElementGuid>7d53b6a1-5fe9-401a-b2c2-b75ee7969dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefits of Dynamics NAV'])[1]/following::a[1]</value>
      <webElementGuid>8658e0a4-a27c-49eb-869d-0c53cf18043b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Dynamics NAV?'])[1]/following::a[1]</value>
      <webElementGuid>9f7a21bb-d53f-4f81-838c-cabac581df75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liberty for User-privileged Pricing &amp; Licensing'])[1]/preceding::a[1]</value>
      <webElementGuid>0953226e-3e1c-4007-ba8f-f74862e531ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Out-of-Office &amp; Right-in-the-Fields for Mobility'])[1]/preceding::a[2]</value>
      <webElementGuid>a5ebcae8-13e6-4f1a-8a6d-a25f847e6048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dynamics NAV Filled with Dosage of Discounts']/parent::*</value>
      <webElementGuid>b4354f99-ccdd-420e-8e1d-092520db0389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-nav-solutions#collapse248')]</value>
      <webElementGuid>587ac9d1-258a-4ba7-a7ba-b4f059d88ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/h4/a</value>
      <webElementGuid>ff0c3b6e-b177-473c-b743-93eeac3c69db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-nav-solutions#collapse248' and (text() = 'Dynamics NAV Filled with Dosage of Discounts ' or . = 'Dynamics NAV Filled with Dosage of Discounts ')]</value>
      <webElementGuid>62581f8f-f599-4768-a0b0-23d2845b2131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
