<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Out-of-Office  Right-in-the-Fields for Mobility</name>
   <tag></tag>
   <elementGuidId>99d535d8-037f-4690-acc2-34d2df24a24c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#247 > h4.panel-title > a.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='247']/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2aea8fd-d4bb-4ecc-8549-2c30ecc73deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse247</value>
      <webElementGuid>6eabce60-b9a2-44e9-9023-a5141ba4d3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4658b0e0-0d8a-465c-baf9-e53f7ade652d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>b3dd3880-414e-40ff-aed0-ffd0de4641a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>1b002436-a230-47dd-b672-28e6757dea47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>c2642d69-5494-416f-b21e-9361cdf76485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-nav-solutions#collapse247</value>
      <webElementGuid>12767c06-4fe5-4b8b-b3f7-6b6d9257405b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c0ad1ce-b8d8-49a2-8793-ba29a1f7b646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Out-of-Office &amp; Right-in-the-Fields for Mobility </value>
      <webElementGuid>d8c9205b-a53b-4ee6-a503-973a1b2ba7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;247&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>c8118dc4-c569-4cdf-be8d-bdbf87eb948c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='247']/h4/a</value>
      <webElementGuid>87e5f544-229a-42a0-97f4-dda9081ef284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Out-of-Office &amp; Right-in-the-Fields for Mobility')]</value>
      <webElementGuid>00f9157a-7bd5-48cb-b9e4-936e44362705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liberty for User-privileged Pricing &amp; Licensing'])[1]/following::a[1]</value>
      <webElementGuid>a7033ca1-2eff-4c68-b89e-f252f4df1677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamics NAV Filled with Dosage of Discounts'])[1]/following::a[2]</value>
      <webElementGuid>c9e820f9-af6b-40a0-afa6-9dc07bbd3562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right-sizing your In-house IT Team &amp; Saving Your Space'])[1]/preceding::a[1]</value>
      <webElementGuid>7226ca89-75a2-4ac1-ae02-d5848817f861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functionality Checklist of Dynamics NAV:'])[1]/preceding::a[2]</value>
      <webElementGuid>5dd837cf-9b10-4645-ab52-c57ff94447bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Out-of-Office &amp; Right-in-the-Fields for Mobility']/parent::*</value>
      <webElementGuid>f85ee827-cc3b-45b7-9a2b-17d8eb8272e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-nav-solutions#collapse247')]</value>
      <webElementGuid>6eef89a8-15ee-4795-919d-1f1852632e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h4/a</value>
      <webElementGuid>0165802c-47e2-4822-bfc9-8649d5f67355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-nav-solutions#collapse247' and (text() = 'Out-of-Office &amp; Right-in-the-Fields for Mobility ' or . = 'Out-of-Office &amp; Right-in-the-Fields for Mobility ')]</value>
      <webElementGuid>63600cd3-a2bf-4492-ab62-30564413d097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
