<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Check the Grid of Industries Below to s_65b76d</name>
   <tag></tag>
   <elementGuidId>0e883cac-9a67-4b0a-a0ec-71ab5ed236f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.widget-3.cus_widget.clearfix > div.col-sm-6 > img.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div[2]/div/div/div/div/div[3]/div/div/div[6]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b57fe6c8-e47a-4498-8547-4c9f7a57b4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>a6bb16b2-01aa-411a-a660-dbb21b83b3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/RBT/media/Raybiztech-Images/nav_image.png</value>
      <webElementGuid>d63fdd63-ae6b-48e1-a5ae-fe4d00b83b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;inrtxt imxtxt&quot;]/div[@class=&quot;main-widget&quot;]/div[@class=&quot;col-sm-12 pad0&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;widget-3 cus_widget clearfix&quot;]/div[@class=&quot;col-sm-6&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>0783af1c-28c7-4e11-8c0c-e85820c6db6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div[2]/div/div/div/div/div[3]/div/div/div[6]/div/div/img</value>
      <webElementGuid>c40070a0-fae5-421e-b290-ab36184b3199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://demo19xperience13.raybiztech.com/RBT/media/Raybiztech-Images/nav_image.png')]</value>
      <webElementGuid>2608c1f2-dc91-48b1-a471-112ea190c925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[6]/div/div/img</value>
      <webElementGuid>51b53da9-1c5e-4137-a8ec-3bc1860ef590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://demo19xperience13.raybiztech.com/RBT/media/Raybiztech-Images/nav_image.png']</value>
      <webElementGuid>94cadaf2-58b7-4a91-8ab4-8e8957fdfe73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
