<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BOOMI - EAI_img-responsive laptop</name>
   <tag></tag>
   <elementGuidId>ffd504f6-6019-4fd3-850d-bad937c7d587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div/div/section/div[2]/div/div/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive.laptop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3d1f765d-0a10-4e93-ac3d-dc721328db4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/admin/RBT/media/RBT-Redesign-Images/laptop.png</value>
      <webElementGuid>37afa2b9-dd8d-4837-b933-9343a4dc969f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive laptop</value>
      <webElementGuid>daa6e3ad-0d67-42de-bd84-1a837c969ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>laptopimage</value>
      <webElementGuid>6c8832dc-e46a-49e4-9d32-b4b3b784783a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;services dell_boomi&quot;]/div[1]/section[@class=&quot;page-banner clouds&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;center&quot;]/div[@class=&quot;row center-item col_2&quot;]/div[@class=&quot;col-md-8 col-md-push-4 col_2_left_side&quot;]/picture[1]/img[@class=&quot;img-responsive laptop&quot;]</value>
      <webElementGuid>4f0a7c65-dff1-4660-98f7-2cb5febf9b47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div/div/section/div[2]/div/div/div/picture/img</value>
      <webElementGuid>ab11cd72-3d5c-4f07-b20c-9daa623dda28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='laptopimage']</value>
      <webElementGuid>9ba5dc52-d668-4437-826b-e91cd99c7490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>30158b65-fee9-4ea2-96bd-decb4e3c0b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://demo19xperience13.raybiztech.com/admin/RBT/media/RBT-Redesign-Images/laptop.png' and @alt = 'laptopimage']</value>
      <webElementGuid>bdffcc9c-6d13-400a-b194-d2bf755e7c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
