<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please enter Phone Number_Phone</name>
   <tag></tag>
   <elementGuidId>a86ab4ff-d9ca-439a-8218-c66eebcc78ae</elementGuidId>
   <imagePath>Screenshots/Targets/Page_AI, Dynamics 365 ERP  CRM, Kentico, Sitecore, Dell Boomi-RBT/input_Please enter Phone Number_Phone.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_AI, Dynamics 365 ERP  CRM, Kentico, Sitecore, Dell Boomi-RBT/input_Please enter Phone Number_Phone.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5189fcc-0210-4dfa-b24d-64139761d36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-elm text-box single-line input-validation-error</value>
      <webElementGuid>026cbde9-fc14-49af-862c-67df0017c9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d46a08e-5738-4fd5-a962-d03bf3923fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Enter Your Phone Number * must be a string with a maximum length of 30.</value>
      <webElementGuid>b2aa5e42-d20d-460f-bcf3-a36b5369c5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>fe6e3b06-75d5-4649-b52c-4f606a945b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Please enter a valid phone number</value>
      <webElementGuid>d1c8d468-3aeb-4b02-b434-32bc810dc4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$</value>
      <webElementGuid>8b62c614-0938-44c0-b6b1-6b7dcce1de93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please enter Phone Number</value>
      <webElementGuid>d39befaf-26a8-4419-babb-4154c8e89916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>0529801b-3798-4ebf-a148-7af9edc6cf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>d0000393-1e50-4b95-a589-6c91b8f4c8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>ac0947e0-7168-4663-a229-6db4f8695f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>185af30f-9849-498f-aa10-e6d5cdcfb40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d192738-03b9-4042-a3c8-fd29aa19f34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Phone-error</value>
      <webElementGuid>be6dab4f-493e-49d7-b5a8-f897e36da0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Phone&quot;)</value>
      <webElementGuid>8ac297f9-946d-45c0-96e3-9d44af3c3aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Phone']</value>
      <webElementGuid>c54c0914-7c5a-4a95-9714-a73d6338379b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divid']/div/div[3]/input</value>
      <webElementGuid>3f66c88b-bcb3-4576-b59d-1768ad764f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/input</value>
      <webElementGuid>aa01948d-b47d-43c7-8577-af5581bcef20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Phone' and @name = 'Phone' and @type = 'text']</value>
      <webElementGuid>fc78b3f2-2374-4b2f-992c-2bf395c8b7ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
