<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Solution-driven approach  Strategic par_7a361d</name>
   <tag></tag>
   <elementGuidId>574cc40d-1931-41ad-a21e-f7b11cb68703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/section/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.banner-text-display > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>592e1471-85d1-47db-a8a1-393029a9ac9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/aboutus-inner.png?ext=.png</value>
      <webElementGuid>bf90cf0e-9686-4fef-9ac6-6ce294a7d7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>117cc4c5-659d-44ad-a2ef-0e103892bbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/section[@class=&quot;inner-banner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;banner-text row&quot;]/div[@class=&quot;col-sm-6 banner-text-display&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>dbd7295c-e150-4b7e-bc90-226a0852526f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/section/div/div/div[2]/img</value>
      <webElementGuid>d9fad832-7e5f-4c96-8776-9ffbc7249ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/aboutus-inner.png?ext=.png')]</value>
      <webElementGuid>8a57aa88-86ec-4c55-944f-7679b80f30ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/img</value>
      <webElementGuid>0994eafa-4c11-4093-b370-e30617bd1c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://demo3xperience13.raybiztech.com/RBT/media/RBT-Images/aboutus-inner.png?ext=.png']</value>
      <webElementGuid>2b3ab37f-d68f-4cbc-83da-794628d3ecff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
