<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kentico Xperience 13 Reporting</name>
   <tag></tag>
   <elementGuidId>06905bcb-f89f-4f39-9fe2-26fe507425d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='k12-solutions']/div/div/div[2]/div/div/div/ul/li[15]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9789fc44-6fe2-45de-ac87-b62df454f86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Reporting</value>
      <webElementGuid>6920051c-b9e3-4eb1-bd29-abb866d5fb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kentico Xperience 13 Reporting</value>
      <webElementGuid>b4b3ea3e-a4c0-41bb-8265-8b4b20b958c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k12-solutions&quot;)/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;row mt-3&quot;]/div[1]/div[@class=&quot;col-sm-12 wow fadeInUp ks13-row animated&quot;]/div[@class=&quot;circle-dot black-dot&quot;]/ul[@class=&quot;request_left_list&quot;]/li[15]/a[1]</value>
      <webElementGuid>01aa1900-17f0-4aef-928e-8047dcd5d731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='k12-solutions']/div/div/div[2]/div/div/div/ul/li[15]/a</value>
      <webElementGuid>468dbfb9-ea99-4783-bbc4-f53e7f17f175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kentico Xperience 13 Reporting')]</value>
      <webElementGuid>1cdbbbd5-ec20-4983-93f0-ddcbe767b76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Performance optimization'])[1]/following::a[1]</value>
      <webElementGuid>dde395ac-3b73-4a9c-9dbf-32d0e8a11a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Document Management'])[1]/following::a[2]</value>
      <webElementGuid>bc96db6e-ecd0-47d3-a72a-bf111ac5ec18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Experienced Kentico Certified Developers'])[1]/preceding::a[1]</value>
      <webElementGuid>15d86c9e-ad9b-40e5-a978-56754c4ff565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leading Kentico Xperience Gold Partner'])[1]/preceding::a[2]</value>
      <webElementGuid>4e63e0e0-a86a-40c6-aeb9-bb393f981983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kentico Xperience 13 Reporting']/parent::*</value>
      <webElementGuid>7f1f8c44-5fbd-4396-be2b-1de84b375244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Reporting')]</value>
      <webElementGuid>29c83f97-4d10-426b-b051-e7cbdaa06da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[15]/a</value>
      <webElementGuid>8b785b08-00df-4cfa-86b8-5611f9b157f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Reporting' and (text() = 'Kentico Xperience 13 Reporting' or . = 'Kentico Xperience 13 Reporting')]</value>
      <webElementGuid>67727965-e7e0-4df9-9b1e-a28fae8596e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
