<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kentico Xperience 13 Technical Support Services</name>
   <tag></tag>
   <elementGuidId>4cd7e76b-1b47-4ec5-9ace-36cfe8d6571d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='k12-solutions']/div/div/div[2]/div/div/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7c3cd4fa-67ee-4f63-b82f-78caac81f4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Technical-Support-Services</value>
      <webElementGuid>e07bd47e-24fd-48b7-b173-2ddde47093d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kentico Xperience 13 Technical Support Services</value>
      <webElementGuid>8f83fc7e-7a9a-4992-82a8-73e17d7b1206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k12-solutions&quot;)/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;row mt-3&quot;]/div[1]/div[@class=&quot;col-sm-12 wow fadeInUp ks13-row animated&quot;]/div[@class=&quot;circle-dot black-dot&quot;]/ul[@class=&quot;request_left_list&quot;]/li[3]/a[1]</value>
      <webElementGuid>473e22fd-8666-4097-9ac4-d4f362f353b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='k12-solutions']/div/div/div[2]/div/div/div/ul/li[3]/a</value>
      <webElementGuid>5588d0f2-59f4-4c5b-8690-5abb41ef4a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kentico Xperience 13 Technical Support Services')]</value>
      <webElementGuid>92da4a6c-826d-498c-8399-869c54dbbf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('FAQ', &quot;'&quot;, 's')])[1]/following::a[1]</value>
      <webElementGuid>09f292c0-a9d7-4841-8dde-e61204c23253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Technical Guide'])[1]/following::a[2]</value>
      <webElementGuid>c591ad92-622f-4476-a9d3-011387f8fa08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge Base'])[1]/preceding::a[1]</value>
      <webElementGuid>402e8e7a-3cdc-4a94-b0a4-6b7f1fc43843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Technical Support Desk'])[1]/preceding::a[2]</value>
      <webElementGuid>ae43a9f3-c3b6-4b9d-88ac-f9e7ae538c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kentico Xperience 13 Technical Support Services']/parent::*</value>
      <webElementGuid>a131f23d-d360-434a-8c5d-da54113403a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Technical-Support-Services')]</value>
      <webElementGuid>db6fdc21-baa8-4660-936e-b1f19fc5eb9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[3]/a</value>
      <webElementGuid>1b079f1b-acf7-42ab-8951-d257c5150730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Technical-Support-Services' and (text() = 'Kentico Xperience 13 Technical Support Services' or . = 'Kentico Xperience 13 Technical Support Services')]</value>
      <webElementGuid>d203aea3-bb02-431f-81c3-853b39b07f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
