<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kentico Xperience 13 Consulting Services_1</name>
   <tag></tag>
   <elementGuidId>c4314e3a-58f9-4cc4-8e9e-bee6e7f586bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='k12-solutions']/div/div/div[2]/div/div/div/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f415daa-cfeb-45a8-8f53-f9d5ebba16b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Xperience-13-Consulting-Services</value>
      <webElementGuid>4ff72664-b9c9-44e0-8513-47a5e870806c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kentico Xperience 13 Consulting Services</value>
      <webElementGuid>7f2c3ede-ffbb-4fae-bdfc-3aba56459e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k12-solutions&quot;)/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;row mt-3&quot;]/div[1]/div[@class=&quot;col-sm-12 wow fadeInUp ks13-row animated&quot;]/div[@class=&quot;circle-dot black-dot&quot;]/ul[@class=&quot;request_left_list&quot;]/li[9]/a[1]</value>
      <webElementGuid>96a83173-1299-4df4-a307-0f2535267286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='k12-solutions']/div/div/div[2]/div/div/div/ul/li[9]/a</value>
      <webElementGuid>c1ed0d7e-b588-4096-8659-f0f81383dea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Kentico Xperience 13 Consulting Services')])[2]</value>
      <webElementGuid>8737e8e9-f819-41f0-90f9-f9578fbf3202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Support Services'])[1]/following::a[1]</value>
      <webElementGuid>242fa6df-78df-46b2-b8a0-52783fd715e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Administrator Demo'])[1]/following::a[2]</value>
      <webElementGuid>a9f499b5-7774-4785-9175-0a19e9299da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Architecture Planning'])[1]/preceding::a[1]</value>
      <webElementGuid>16c21973-8605-416f-b566-71e284f1ec74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Integration Services'])[2]/preceding::a[2]</value>
      <webElementGuid>bac4b28f-61ce-4823-9637-6976e4467db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Xperience-13-Consulting-Services')]</value>
      <webElementGuid>ec1fbbd9-8d1c-45fd-a398-5fb791cc87f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[9]/a</value>
      <webElementGuid>edb894bb-b67e-480c-a1b0-6770b355fd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/Kentico-Xperience-13-Consulting-Services' and (text() = 'Kentico Xperience 13 Consulting Services' or . = 'Kentico Xperience 13 Consulting Services')]</value>
      <webElementGuid>4878a437-8abf-401a-b3bd-ff20d15dadd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
