<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kentico Xperience 13 License Price List</name>
   <tag></tag>
   <elementGuidId>324a6174-2672-498d-8f49-560f5c39ce05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='k12-solutions']/div/div/div[2]/div/div/div/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19c40719-69c8-4624-a649-f1592f4f9a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/kentico-license-price-list</value>
      <webElementGuid>c82e0c4c-bbea-4534-8821-1d3bc12ed6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kentico Xperience 13 License Price List</value>
      <webElementGuid>fd4143a6-dfd6-4c17-aad1-17aef508e3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k12-solutions&quot;)/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;row mt-3&quot;]/div[1]/div[@class=&quot;col-sm-12 wow fadeInUp ks13-row animated&quot;]/div[@class=&quot;circle-dot black-dot&quot;]/ul[@class=&quot;request_left_list&quot;]/li[6]/a[1]</value>
      <webElementGuid>656ba81f-a20d-45e1-827e-e3a9c8d1b111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='k12-solutions']/div/div/div[2]/div/div/div/ul/li[6]/a</value>
      <webElementGuid>6f123ed9-7a2f-4c1b-bf06-d2f5aee6c1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kentico Xperience 13 License Price List')]</value>
      <webElementGuid>16b44aed-00d0-48c4-8825-744c934f8278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Technical Support Desk'])[1]/following::a[1]</value>
      <webElementGuid>ac8bc532-2218-4c7a-8342-c0145d29610f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge Base'])[1]/following::a[2]</value>
      <webElementGuid>e3394979-30f7-4fe8-9ba0-932d4663d832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Administrator Demo'])[1]/preceding::a[1]</value>
      <webElementGuid>ca6e7a7c-bacb-4aa0-951a-c5da4f7c0af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kentico Xperience 13 Support Services'])[1]/preceding::a[2]</value>
      <webElementGuid>b8d8eb91-b605-41fd-8a16-2e4cc847308e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kentico Xperience 13 License Price List']/parent::*</value>
      <webElementGuid>863b2d76-3124-422b-9fe4-5011e55f06af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/kentico-license-price-list')]</value>
      <webElementGuid>72e179e8-2147-47e6-9585-cd4b7248ecf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li[6]/a</value>
      <webElementGuid>113bbbbf-ab5f-4268-8fe3-56243ca932c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/solutions/epcm/kentico-xperience-13/kentico-license-price-list' and (text() = 'Kentico Xperience 13 License Price List' or . = 'Kentico Xperience 13 License Price List')]</value>
      <webElementGuid>8e3c264c-ffd5-485c-8902-30853986c114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
