<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Kentico Xperience 13</name>
   <tag></tag>
   <elementGuidId>605285a4-946e-43f1-b53d-9bb0126f5fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div/div/div/div/div/div/div[2]/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.banner_heading2.hidden-xs.wow.fadeInLeft.animated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>84f075c4-473f-458d-b033-d6ec17e58232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner_heading2 hidden-xs wow fadeInLeft animated</value>
      <webElementGuid>ec695149-81db-419d-81e4-6ea4284f44db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wow-delay</name>
      <type>Main</type>
      <value>0.5s</value>
      <webElementGuid>48173b04-c457-4614-a7d4-3ddd89544dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wow-duration</name>
      <type>Main</type>
      <value>0.25s</value>
      <webElementGuid>24af9bfb-ac48-47a5-b2c0-89d9baa927ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kentico Xperience 13 </value>
      <webElementGuid>5ae0d0c3-050f-47ef-95e6-d3a09f109080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;services test&quot;]/div[1]/div[@class=&quot;banner-bg page-banner kenticobanner-13&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;center&quot;]/div[@class=&quot;row center-item col_2&quot;]/div[@class=&quot;col-md-4 col-md-pull-8 pl-banner col_2_right_side&quot;]/h1[@class=&quot;banner_heading2 hidden-xs wow fadeInLeft animated&quot;]</value>
      <webElementGuid>ff6dbf90-bd32-419e-a3c6-ae9271709c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div/div/div/div/div/div/div[2]/h1</value>
      <webElementGuid>53b89558-8de8-4c17-a825-e4a7d4f65fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KENTICO Xperience 13'])[1]/following::h1[1]</value>
      <webElementGuid>28810170-4ba8-4f93-8368-89755fab48d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::h1[1]</value>
      <webElementGuid>f844602c-2f9a-4f8b-a16a-07c0aea52a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KENTICO XPERIENCE SOLUTIONS'])[1]/preceding::h1[1]</value>
      <webElementGuid>369b768b-835e-4997-a655-16d7473d74c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kentico Xperience 13']/parent::*</value>
      <webElementGuid>9f00dc58-f655-41bb-bd58-bdefcae82e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h1</value>
      <webElementGuid>d0873a72-ae7d-447b-8cc6-392e7d5954d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Kentico Xperience 13 ' or . = 'Kentico Xperience 13 ')]</value>
      <webElementGuid>01c6902e-d830-4669-baf5-c89582ed9c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
