<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_KENTICO Xperience 13_img-responsive</name>
   <tag></tag>
   <elementGuidId>0c901717-f676-42ec-971b-0a9a243fff3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='post']/main/div/div/div/div/div/div/div/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>picture.kentico-12-banner-laptop > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>678e483e-c2d2-45bf-ae75-1ed7a747af6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/admin/RBT/media/RBT-Redesign-Images/kenticobanner13page.jpg</value>
      <webElementGuid>0e7767ce-223a-41c9-981f-1a9aed02e398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>6eba7657-420c-428d-a06e-b4802438c0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>laptopimage</value>
      <webElementGuid>e8918c2b-227d-4dc0-a484-c003da0fc56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post&quot;)/main[1]/div[@class=&quot;services test&quot;]/div[1]/div[@class=&quot;banner-bg page-banner kenticobanner-13&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;center&quot;]/div[@class=&quot;row center-item col_2&quot;]/div[@class=&quot;col-md-8 col-md-push-4 col_2_left_side&quot;]/picture[@class=&quot;kentico-12-banner-laptop&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>9e854aca-c7f6-4d10-9a3b-83de3cee3e93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div/div/div/div/div/div/div/picture/img</value>
      <webElementGuid>423895be-6c78-49ba-8756-6ae611a322dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='laptopimage']</value>
      <webElementGuid>38e463e5-e880-4e41-bbff-25d26c599116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>980fe359-e0a4-4b89-b6bc-8f67ea436e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://demo3xperience13.raybiztech.com/admin/RBT/media/RBT-Redesign-Images/kenticobanner13page.jpg' and @alt = 'laptopimage']</value>
      <webElementGuid>4882b6ed-fba7-4f38-aca9-48508aae7a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
