<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Message_btn_Submit1</name>
   <tag></tag>
   <elementGuidId>3d1b3339-ae3b-473e-93d0-2a43562c33fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btn_Submit1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_Submit1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>728b1f68-3747-44c5-bd80-9b77b10e8161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5842341b-4b34-4fb2-9084-2a7d18935755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Submit1</value>
      <webElementGuid>d08b5237-6f04-4d3a-8e94-77226bb1e504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-button btn-transparent-primary mb-20 btn-large</value>
      <webElementGuid>37a91b64-e2f1-4617-b525-c5bd88897a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SUBMIT NOW</value>
      <webElementGuid>56adabf7-8462-4c7b-8c37-e701d6d7baf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Submit1&quot;)</value>
      <webElementGuid>1688f066-d36b-493f-bf21-379138964ad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn_Submit1']</value>
      <webElementGuid>5bf5d547-d563-4fab-84f6-30498c83af7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='post']/main/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/form/div[8]/input</value>
      <webElementGuid>48bb3736-ccb8-414f-a946-3b19804df26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>0dd02943-530c-4c09-878b-5db4b101c7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btn_Submit1']</value>
      <webElementGuid>433c923c-64b6-423b-80f8-c1cb2790eb65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
