<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_toggle On-the-Fields  Off-the-Facility Services</name>
   <tag></tag>
   <elementGuidId>348dadef-bfbe-4617-a446-ecb77a923032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#heading4 > h4.panel-title > a.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='heading4']/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>229f89a4-98fa-4d84-879b-6cb61c4b6c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseFour</value>
      <webElementGuid>ed92009e-c426-4dc2-99e2-55a2e35cfe94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8616d3d7-ae88-4203-9c75-2d0b0caf0cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>deb1ca7f-d1f1-4cb1-91e4-7ea6194789fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>d1fc84c5-e717-4283-b634-a39aa83769bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>e650bf53-ca32-439d-9eec-747b8a4ae333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-ax-solutions#collapseFour</value>
      <webElementGuid>d5eee970-a48b-45f4-a711-5fc57b646698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3215a96e-11cc-48dc-ac47-8dabdeb7fdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>toggle On-the-Fields &amp; Off-the-Facility Services </value>
      <webElementGuid>a32e7f17-78fe-4a33-8759-3557a239b107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading4&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>5226e0b7-7b5a-424c-925c-a73f88b57442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='heading4']/h4/a</value>
      <webElementGuid>7c238f62-7da2-44be-8b26-382f368d9176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[2]/following::a[1]</value>
      <webElementGuid>11d788c0-9683-45f6-b650-510127a11cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[1]/following::a[2]</value>
      <webElementGuid>8330c6ab-9767-47cf-ad8c-40d7651da8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On-the-Fields &amp; Off-the-Facility Services']/parent::*</value>
      <webElementGuid>45c18566-6e58-4693-97c1-e5215b9db2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-ax-solutions#collapseFour')]</value>
      <webElementGuid>b442a917-2ed2-47b2-8dd9-798937329f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/h4/a</value>
      <webElementGuid>a373da4e-56a4-4313-8fef-450bbebcaff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-ax-solutions#collapseFour' and (text() = 'toggle On-the-Fields &amp; Off-the-Facility Services ' or . = 'toggle On-the-Fields &amp; Off-the-Facility Services ')]</value>
      <webElementGuid>a9a1849c-52ca-4a59-8f25-7a488f12b2e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
