<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_toggle Regulatory Compliance Management</name>
   <tag></tag>
   <elementGuidId>09221e33-f679-486f-bbfe-1fdf16222c00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#heading5 > h4.panel-title > a.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='heading5']/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14041d5b-add1-4bd8-a8ff-69d0ed4c931a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseFive</value>
      <webElementGuid>44e2cdb2-9ce8-4fc4-bfca-f77295b8badc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84f45fee-bae6-44c7-bb2b-9caf5458b414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>d47f7080-6439-41af-b2aa-2398c9446aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>0c09cc9c-7e60-4ef9-bda8-5ff8386ef10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>58ea4431-e4ec-45f7-88cc-b802a985f33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-ax-solutions#collapseFive</value>
      <webElementGuid>d3905f04-15f3-476f-95a9-a0b8889ad3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3598dddc-678f-47f1-964d-7a8a2295a804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>toggle Regulatory Compliance Management </value>
      <webElementGuid>84855be2-e84b-4066-b2eb-b574615fe574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading5&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>028e97b7-d584-4cea-b0cb-6026329c6b6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='heading5']/h4/a</value>
      <webElementGuid>4c927bc6-2e25-479e-afea-08712344ba21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[3]/following::a[1]</value>
      <webElementGuid>3db84ef0-8de8-40ed-93bb-0b74ab96eb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gains transparency on regulatory policies'])[1]/preceding::a[1]</value>
      <webElementGuid>6c6e8a02-a012-4731-a2dc-fd10801bc0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Regulatory Compliance Management']/parent::*</value>
      <webElementGuid>e0a50d3d-27ed-49b5-9395-6317088dfa48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-ax-solutions#collapseFive')]</value>
      <webElementGuid>bc58899c-7f5c-4e2e-b5e6-c6dbc82fbed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/h4/a</value>
      <webElementGuid>4948272c-c50a-48a7-85d3-6231a3dcae51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-ax-solutions#collapseFive' and (text() = 'toggle Regulatory Compliance Management ' or . = 'toggle Regulatory Compliance Management ')]</value>
      <webElementGuid>b02deb99-e622-4948-b1f6-8edbb40be478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
