<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The evolution of Dynamics AX has resulted_b096f2</name>
   <tag></tag>
   <elementGuidId>b3061ac3-a6dc-4287-bb22-a4f1d1ca7f3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collapseThree > div.panel-body > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseThree']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>edb41d86-9c13-445e-a683-a23f16dc0b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The evolution of Dynamics AX has resulted in a crystal clean, modern UI that puts the right information at your fingertips. The mission-critical Dynamics AX is for all those like you who follow the cloud-first approach. The Office-mix solution enables the end-users to enjoy the same quality of experience while they are browsing their desktop, laptop, tablet or mobile phone.</value>
      <webElementGuid>2a553c9f-7591-4834-958d-3b2a8d8db52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseThree&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>1c4378bc-05d7-4273-b420-36fda45c5215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseThree']/div/p</value>
      <webElementGuid>7cace194-3a15-48f6-a850-947d344dfa78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[2]/following::p[1]</value>
      <webElementGuid>57bb6f1d-be37-4e10-8540-2eed9d06c2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[1]/following::p[2]</value>
      <webElementGuid>e83aa5b4-4b63-401d-a6c7-684741d4d484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[3]/preceding::p[1]</value>
      <webElementGuid>0a7b6355-1a83-4ad5-9b0a-7236cdc158b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The evolution of Dynamics AX has resulted in a crystal clean, modern UI that puts the right information at your fingertips. The mission-critical Dynamics AX is for all those like you who follow the cloud-first approach. The Office-mix solution enables the end-users to enjoy the same quality of experience while they are browsing their desktop, laptop, tablet or mobile phone.']/parent::*</value>
      <webElementGuid>d36e86c8-320b-4f05-86f4-c8e2ea8be019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/p</value>
      <webElementGuid>f0dbd956-3d04-4814-8fe0-d4a0fa3c080e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The evolution of Dynamics AX has resulted in a crystal clean, modern UI that puts the right information at your fingertips. The mission-critical Dynamics AX is for all those like you who follow the cloud-first approach. The Office-mix solution enables the end-users to enjoy the same quality of experience while they are browsing their desktop, laptop, tablet or mobile phone.' or . = 'The evolution of Dynamics AX has resulted in a crystal clean, modern UI that puts the right information at your fingertips. The mission-critical Dynamics AX is for all those like you who follow the cloud-first approach. The Office-mix solution enables the end-users to enjoy the same quality of experience while they are browsing their desktop, laptop, tablet or mobile phone.')]</value>
      <webElementGuid>5e58cf19-d28e-4469-806c-20e9c4a249e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
