<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_togglePurpose for the Relationship Insights</name>
   <tag></tag>
   <elementGuidId>f8c81f9b-e025-452b-a0fc-7ac31d40949b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headingTwo']/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5138a448-da21-4b5e-8196-fc8f1fbde723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseTwo</value>
      <webElementGuid>f8afdfe4-73b0-4f19-b9a8-0b7c8f583a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6a912c1-6b95-4004-8acc-0cdb0e1dff68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>d6832cc6-7862-410a-84a6-ff002e3f5f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>c70a7597-09f2-41db-b1df-0b9de71a0845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>65b9ca30-1671-49ca-be26-409eec339a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseTwo</value>
      <webElementGuid>3130a503-66aa-4782-958a-ab3572cbe06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64aa62a5-2a68-45de-bb4c-f825bd66a6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>togglePurpose for the “Relationship Insights” </value>
      <webElementGuid>7e7529a4-b1db-472c-9dbb-362402e07cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headingTwo&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>eb590cb7-bd7e-46b8-8fb9-de36d6c302eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1a0affcf-6dea-4e2c-b74d-c2159e4fbce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseTwo</value>
      <webElementGuid>52295656-c557-4ad6-b837-96b4d7306d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f134e8a6-908c-486c-95b0-401cd4af0ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>52b4b34e-4960-404c-abc6-88aa0e656251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>17441dc6-3bb4-4d2f-bb79-1ba404df381b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>b732770d-b92a-4277-9633-fde5201f39b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseTwo</value>
      <webElementGuid>892306b0-bd8b-4b71-b7c5-e54d1219e7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>717ee674-0e81-449e-ba0b-933f8a1e195d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>togglePurpose for the “Relationship Insights” </value>
      <webElementGuid>4dd7e51d-41f9-43ac-a07f-9e1de2c85e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headingTwo&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>bcc09bfd-0a26-4fa0-8f07-0e3cc0d647fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec97fd8a-4f24-4ebc-a070-78302ffa7afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseTwo</value>
      <webElementGuid>e034c91f-56ca-400a-ab0f-068bcae2e32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b3691cd-4755-41bc-b3a6-8400b75efc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>aa6175ce-2236-4066-836f-aba59f9f8087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>d3edee3f-ddeb-4f93-8464-6a54162adc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>83aceff2-ee79-4d23-8435-64f1b4a12d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseTwo</value>
      <webElementGuid>0ee2853e-4d1f-462b-b2dd-b7b64c49c07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67a74d01-8ba9-458f-a579-ffe89d0b8b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>togglePurpose for the “Relationship Insights” </value>
      <webElementGuid>2de64982-5d83-4043-b879-128c9ad4d928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headingTwo&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>d3216c7a-db98-41eb-999a-c269bcd5e68e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headingTwo']/h4/a</value>
      <webElementGuid>c05bb4a0-ced3-4057-bd12-fcf690e4cb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamics 365 integration with Office 365'])[1]/following::a[1]</value>
      <webElementGuid>24100a91-9773-415f-8cc8-51fffc4749c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[1]/following::a[1]</value>
      <webElementGuid>1d15f167-af42-4ca1-a22b-656cffae525c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purpose for the “Relationship Insights”']/parent::*</value>
      <webElementGuid>cbf7e4b7-a3db-49c9-ac82-4fceb8737159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseTwo')]</value>
      <webElementGuid>b8deff1b-e204-415d-ac69-5be829739eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h4/a</value>
      <webElementGuid>bb6701cf-a504-41db-9c0e-1c8cf9abbb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseTwo' and (text() = 'togglePurpose for the “Relationship Insights” ' or . = 'togglePurpose for the “Relationship Insights” ')]</value>
      <webElementGuid>34648137-8bb8-43f0-879d-89e6512a4d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseTwo')]</value>
      <webElementGuid>53582516-ef48-4115-a8df-d6bc4d5b4da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseTwo' and (text() = 'togglePurpose for the “Relationship Insights” ' or . = 'togglePurpose for the “Relationship Insights” ')]</value>
      <webElementGuid>02a425e0-7f06-46cd-842c-5fe7d8f3d211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
