<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_toggleCreating Custom Learning Path using_99b77a</name>
   <tag></tag>
   <elementGuidId>9dd9c11e-2614-4ada-bc9a-027b2c4d2b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headingThree']/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headingThree > h4.panel-title > a.collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b01bd979-5084-47fd-85fd-f1775c6d80bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseThree</value>
      <webElementGuid>f6aa5429-15da-4d4b-beba-7a5e795eb605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8466f9a8-5f81-4512-a97c-80711d5d4531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>e3eeba7d-fab6-41e6-9e74-be90f4d02e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>06ea8f84-6527-4321-8608-75a65138cc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>4e995492-790d-48c3-96c1-8a37401a813d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseThree</value>
      <webElementGuid>c1cd5478-24c7-4efd-95fe-def7ef86348b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63609e3d-5f0b-4ff4-85d7-596ddf2f4ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>toggleCreating Custom Learning Path using Dynamics 365 </value>
      <webElementGuid>7d0c6239-de8a-4e89-955a-c9f17465b232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headingThree&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>20a929d6-5799-4867-a2bd-8278b8e65f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49977f59-6ba2-41fd-b23f-1023a09f437d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapseThree</value>
      <webElementGuid>69f994bc-5290-4f21-836a-0677750fb02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>025d4847-3efc-4353-b973-775001f64eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsed</value>
      <webElementGuid>2679b7a0-e565-447c-a84e-21a8738c0158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#accordion</value>
      <webElementGuid>1920f759-e581-4069-b316-bdfa2c626c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>2386b2fc-8f89-470d-a724-c632676683ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo3xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseThree</value>
      <webElementGuid>08ad5c0e-3ffa-43de-a1cc-891de82ce084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6efda3b2-e34d-4a0f-910b-fd9479dcf9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>toggleCreating Custom Learning Path using Dynamics 365 </value>
      <webElementGuid>b9e79dd9-8462-4663-851e-80d70ffe7b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headingThree&quot;)/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]</value>
      <webElementGuid>81db413a-7cf7-481f-ad86-14cd539da4b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headingThree']/h4/a</value>
      <webElementGuid>c07d5e46-b9fc-4100-a0ea-9ac0e034706c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[2]/following::a[1]</value>
      <webElementGuid>1e35711e-8450-4a54-a6d8-822c5d81dca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Creating Custom Learning Path using Dynamics 365']/parent::*</value>
      <webElementGuid>1b14fc31-15c1-46bc-aa73-724628f18feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseThree')]</value>
      <webElementGuid>7c0e27e5-1153-417e-a8f8-5574731060e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h4/a</value>
      <webElementGuid>ac0dc506-f0ee-4e39-97f8-d1cba55221ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo19xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseThree' and (text() = 'toggleCreating Custom Learning Path using Dynamics 365 ' or . = 'toggleCreating Custom Learning Path using Dynamics 365 ')]</value>
      <webElementGuid>4b49fbf5-8066-4100-a916-6aee9b24e155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo3xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseThree')]</value>
      <webElementGuid>b6810069-d395-4593-94f3-f3055fa65300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo3xperience13.raybiztech.com/solutions/enterprise-resource-planning/microsoft-dynamics-365#collapseThree' and (text() = 'toggleCreating Custom Learning Path using Dynamics 365 ' or . = 'toggleCreating Custom Learning Path using Dynamics 365 ')]</value>
      <webElementGuid>375a73cc-a0df-4408-88c3-5a19495b8d86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
