<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Connected field service is the highly reg_925483</name>
   <tag></tag>
   <elementGuidId>05cd424e-a645-4e3d-ab04-975da6a0e730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse5']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapse5 > div.panel-body > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>eb9057ec-7378-4057-84ac-a84ff4a95501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connected field service is the highly regarded released feature that remotely monitors the customers’ equipment. It assists the service organizations to navigate from the expensive break-fix model to a friendly one that combines monitoring/support elements with IoT and machine learning.</value>
      <webElementGuid>0a2166ba-9c15-4383-bc9e-3dfc3cb68438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse5&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>f8ab12ad-0c65-447f-bc0c-76f7e77c8c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ee74f3e4-47cf-4a73-9bd7-0a9d434383f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connected field service is the highly regarded released feature that remotely monitors the customers’ equipment. It assists the service organizations to navigate from the expensive break-fix model to a friendly one that combines monitoring/support elements with IoT and machine learning.</value>
      <webElementGuid>387aebc9-7df9-4fca-af26-a0398545e3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse5&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>cab894b4-37a7-4e98-ac86-0fb6f95769c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8710c934-151a-468f-868c-9cc37f27191c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connected field service is the highly regarded released feature that remotely monitors the customers’ equipment. It assists the service organizations to navigate from the expensive break-fix model to a friendly one that combines monitoring/support elements with IoT and machine learning.</value>
      <webElementGuid>fff807c6-0c56-469e-9b13-354c06c250d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse5&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>38641435-c381-4e3f-bdab-4b4375b26e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse5']/div/p</value>
      <webElementGuid>5da8880d-8132-48ed-92a9-33cde7667161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[4]/following::p[1]</value>
      <webElementGuid>eeedef14-44f1-4068-bb3d-c423d3b1af08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[5]/preceding::p[1]</value>
      <webElementGuid>2e27b84c-2b34-45a6-aaa1-be722de65f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Connected field service is the highly regarded released feature that remotely monitors the customers’ equipment. It assists the service organizations to navigate from the expensive break-fix model to a friendly one that combines monitoring/support elements with IoT and machine learning.']/parent::*</value>
      <webElementGuid>32ce00af-a975-41cd-b5a7-fffd3f090ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/p</value>
      <webElementGuid>e3421172-23e3-4dc5-be1b-6e72234b49c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Connected field service is the highly regarded released feature that remotely monitors the customers’ equipment. It assists the service organizations to navigate from the expensive break-fix model to a friendly one that combines monitoring/support elements with IoT and machine learning.' or . = 'Connected field service is the highly regarded released feature that remotely monitors the customers’ equipment. It assists the service organizations to navigate from the expensive break-fix model to a friendly one that combines monitoring/support elements with IoT and machine learning.')]</value>
      <webElementGuid>65b506b2-bd94-4fb0-bccc-1803c68e00a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
