<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Microsoft Dynamics CRM Online 2016 Update_c0b55f</name>
   <tag></tag>
   <elementGuidId>67d9e46a-b23d-4f53-82be-bd459cbc0c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseThree']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapseThree > div.panel-body > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c9508d60-3c36-41d8-89f1-e8df6db82480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>‘Microsoft Dynamics CRM Online 2016 Update allows you to create contextually-rich Learning Path for the enrichment of your employees. Learning Path provides great ways to help people become familiar with business forms. This helps in reducing the training time, costs and enable team productivity.</value>
      <webElementGuid>e104117f-9646-418e-8dd0-aa518a269b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseThree&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>a505c02a-25ef-4dbc-88bb-7d761b3a3cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9f3fab96-3094-4224-8b9f-87a1becddd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>‘Microsoft Dynamics CRM Online 2016 Update allows you to create contextually-rich Learning Path for the enrichment of your employees. Learning Path provides great ways to help people become familiar with business forms. This helps in reducing the training time, costs and enable team productivity.</value>
      <webElementGuid>a501a9a0-bf58-4055-9dde-ce610fde86fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseThree&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>fbc591ef-b076-45bf-9ed9-816b52df500b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4884be3f-a2f9-4df6-8122-54ca7daec0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>‘Microsoft Dynamics CRM Online 2016 Update allows you to create contextually-rich Learning Path for the enrichment of your employees. Learning Path provides great ways to help people become familiar with business forms. This helps in reducing the training time, costs and enable team productivity.</value>
      <webElementGuid>a710dab0-ff14-4886-ba94-7786fd592dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseThree&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>33795256-51f9-49a6-a97c-caeba0ae27bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseThree']/div/p</value>
      <webElementGuid>6c13a94d-4e6f-4b05-8ee6-524743eb5111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[3]/following::p[1]</value>
      <webElementGuid>2c29f35f-3713-4f36-a565-d6094e785b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[4]/preceding::p[1]</value>
      <webElementGuid>6d904f1f-3142-4505-8913-0b36c85a015d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='‘Microsoft Dynamics CRM Online 2016 Update allows you to create contextually-rich Learning Path for the enrichment of your employees. Learning Path provides great ways to help people become familiar with business forms. This helps in reducing the training time, costs and enable team productivity.']/parent::*</value>
      <webElementGuid>abf16474-4857-41a4-8fce-f9bf2ce4b01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[3]/div[2]/div/p</value>
      <webElementGuid>96e66686-70e1-48d7-b1bc-be5826e33078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '‘Microsoft Dynamics CRM Online 2016 Update allows you to create contextually-rich Learning Path for the enrichment of your employees. Learning Path provides great ways to help people become familiar with business forms. This helps in reducing the training time, costs and enable team productivity.' or . = '‘Microsoft Dynamics CRM Online 2016 Update allows you to create contextually-rich Learning Path for the enrichment of your employees. Learning Path provides great ways to help people become familiar with business forms. This helps in reducing the training time, costs and enable team productivity.')]</value>
      <webElementGuid>18b5104a-2ebc-4974-9f20-8d47640e0a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
