<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Resource scheduling optimization enables _0cead4</name>
   <tag></tag>
   <elementGuidId>b37e62af-383b-4408-a88a-e7c7c7297c08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse6']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapse6 > div.panel-body > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>de0d1ab4-7de9-42b4-9c0b-dbe2cabb98f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resource scheduling optimization enables the system to schedule several items on a recurring basis. The schedulable resource optimizer takes account of the constraints while optimizing schedules such as the presence of the resource, skills, task priority, and time windows.</value>
      <webElementGuid>74746b73-c5c5-4d13-b791-e6428b6fb1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse6&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>66d46af7-797d-4f0b-8300-a12fb01a7523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c34768e3-4844-4834-a14f-b9f2192c2d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resource scheduling optimization enables the system to schedule several items on a recurring basis. The schedulable resource optimizer takes account of the constraints while optimizing schedules such as the presence of the resource, skills, task priority, and time windows.</value>
      <webElementGuid>505f7dd2-88e7-49ad-8be0-192f4381aa39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse6&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>64022b3b-07b1-4030-959f-4cab4cb20bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>86b1fe80-2367-4ed8-8467-4dae5c9d0040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resource scheduling optimization enables the system to schedule several items on a recurring basis. The schedulable resource optimizer takes account of the constraints while optimizing schedules such as the presence of the resource, skills, task priority, and time windows.</value>
      <webElementGuid>08a4bdf1-9668-4d24-851a-cc4a277f04b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse6&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>663182b0-e900-4172-8dd5-7c8f0113de54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse6']/div/p</value>
      <webElementGuid>d2961e2f-1506-4d92-af8b-5a8726a5a485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[5]/following::p[1]</value>
      <webElementGuid>a6d13051-e9ab-4209-8d6f-155f557b2fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[6]/preceding::p[1]</value>
      <webElementGuid>617aae10-9dd5-4ea8-a952-bca6fb73ee49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resource scheduling optimization enables the system to schedule several items on a recurring basis. The schedulable resource optimizer takes account of the constraints while optimizing schedules such as the presence of the resource, skills, task priority, and time windows.']/parent::*</value>
      <webElementGuid>751c4d8f-1a4e-4504-9878-547a59f40973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/p</value>
      <webElementGuid>8fc2d0bf-1550-4368-8a6b-a4f2eca44dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Resource scheduling optimization enables the system to schedule several items on a recurring basis. The schedulable resource optimizer takes account of the constraints while optimizing schedules such as the presence of the resource, skills, task priority, and time windows.' or . = 'Resource scheduling optimization enables the system to schedule several items on a recurring basis. The schedulable resource optimizer takes account of the constraints while optimizing schedules such as the presence of the resource, skills, task priority, and time windows.')]</value>
      <webElementGuid>39081a1d-7a73-46ba-a867-e73947ba26f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
