<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The corporate software rests over the bed_a588d2</name>
   <tag></tag>
   <elementGuidId>9c511dd1-3a21-4e8d-ae99-301ef2378004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse16']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapse16 > div.panel-body > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d9e6a2bd-88d1-4764-9695-37cc152a68eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The corporate software rests over the bed of complicated databases that are customized for different organizations. Microsoft has been struggling to drift away from the complexities of customizations. Necessity is the mother of invention, this phraseology gels well with Microsoft that has forced CDM to tightly integrate with Office 365 and other apps with a standardized API.</value>
      <webElementGuid>e4a306a8-4540-4334-9365-726361e59422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse16&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>e12b91bd-e91f-4d22-be2d-7c2d02fb13f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>87f2f7dd-e6ea-4411-a5fa-7a1991bbfeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The corporate software rests over the bed of complicated databases that are customized for different organizations. Microsoft has been struggling to drift away from the complexities of customizations. Necessity is the mother of invention, this phraseology gels well with Microsoft that has forced CDM to tightly integrate with Office 365 and other apps with a standardized API.</value>
      <webElementGuid>060263b5-7d65-4dcc-a9fa-647553872343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse16&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>9623e027-35e5-4ecc-a439-70cd2407f513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f1708500-0115-4c26-ab86-4e63cd8ed1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The corporate software rests over the bed of complicated databases that are customized for different organizations. Microsoft has been struggling to drift away from the complexities of customizations. Necessity is the mother of invention, this phraseology gels well with Microsoft that has forced CDM to tightly integrate with Office 365 and other apps with a standardized API.</value>
      <webElementGuid>4a513f49-9aa5-4187-8d0a-f4a12a735372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse16&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>c701d221-4acb-42ac-b98b-9729ea96d01c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse16']/div/p</value>
      <webElementGuid>4714e28b-8d27-4c33-9700-0b468f724e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[14]/following::p[1]</value>
      <webElementGuid>a716f78d-eb30-4ca9-85b7-f73f16e39f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[15]/preceding::p[1]</value>
      <webElementGuid>fc7f926d-2ff8-45c9-b09b-19b0ce85e14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The corporate software rests over the bed of complicated databases that are customized for different organizations. Microsoft has been struggling to drift away from the complexities of customizations. Necessity is the mother of invention, this phraseology gels well with Microsoft that has forced CDM to tightly integrate with Office 365 and other apps with a standardized API.']/parent::*</value>
      <webElementGuid>74dea00f-d188-4d6a-bc31-4f314c9add0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/p</value>
      <webElementGuid>3090d85d-690a-416d-a779-3cb3ab0ab298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The corporate software rests over the bed of complicated databases that are customized for different organizations. Microsoft has been struggling to drift away from the complexities of customizations. Necessity is the mother of invention, this phraseology gels well with Microsoft that has forced CDM to tightly integrate with Office 365 and other apps with a standardized API.' or . = 'The corporate software rests over the bed of complicated databases that are customized for different organizations. Microsoft has been struggling to drift away from the complexities of customizations. Necessity is the mother of invention, this phraseology gels well with Microsoft that has forced CDM to tightly integrate with Office 365 and other apps with a standardized API.')]</value>
      <webElementGuid>e13755da-2023-4faf-8e50-19b0e124ff45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
