<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_This is an email engagement tool that is _6730ed</name>
   <tag></tag>
   <elementGuidId>7c6ece94-873d-4e13-b66e-e5790a86b6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseTwo']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapseTwo > div.panel-body > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>63810edf-5483-48d0-a9c7-20316f140b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is an email engagement tool that is inserted with relationship assistant, email engagement and auto-capture for amplifying your business strengths. It generates instant-reminder alerts about your upcoming activities, phone calls, meetings and trace relevant messages from your exchange server.</value>
      <webElementGuid>e258abe6-2d74-4577-ba44-4f40b2f1d3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseTwo&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>7d155ed0-b3bb-4bd2-97d0-c28aebc1f587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>32105da5-ec66-42c4-835c-1c40568efd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is an email engagement tool that is inserted with relationship assistant, email engagement and auto-capture for amplifying your business strengths. It generates instant-reminder alerts about your upcoming activities, phone calls, meetings and trace relevant messages from your exchange server.</value>
      <webElementGuid>3d03fe71-b542-4c43-a120-ca2667713fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseTwo&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>723a1c62-3071-4214-aa9c-379fdee49a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a9665619-5847-4645-a906-d3ccb2f897a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is an email engagement tool that is inserted with relationship assistant, email engagement and auto-capture for amplifying your business strengths. It generates instant-reminder alerts about your upcoming activities, phone calls, meetings and trace relevant messages from your exchange server.</value>
      <webElementGuid>f8961370-d420-4546-836d-a94c77ecbecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseTwo&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>2088117b-7769-444b-a6da-4600695105ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseTwo']/div/p</value>
      <webElementGuid>0a353ce1-8af6-47f2-9309-b8e2a2031516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[2]/following::p[1]</value>
      <webElementGuid>c6f1e3de-44b5-4f16-a8d1-285e25397e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[3]/preceding::p[1]</value>
      <webElementGuid>3af84123-e791-43bc-946d-9eaa5cedc8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is an email engagement tool that is inserted with relationship assistant, email engagement and auto-capture for amplifying your business strengths. It generates instant-reminder alerts about your upcoming activities, phone calls, meetings and trace relevant messages from your exchange server.']/parent::*</value>
      <webElementGuid>9d9bf462-a2c5-4eff-a652-d72c45f7df44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div[2]/div/p</value>
      <webElementGuid>f36b3742-cb21-47c2-967e-17635c2aba6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'This is an email engagement tool that is inserted with relationship assistant, email engagement and auto-capture for amplifying your business strengths. It generates instant-reminder alerts about your upcoming activities, phone calls, meetings and trace relevant messages from your exchange server.' or . = 'This is an email engagement tool that is inserted with relationship assistant, email engagement and auto-capture for amplifying your business strengths. It generates instant-reminder alerts about your upcoming activities, phone calls, meetings and trace relevant messages from your exchange server.')]</value>
      <webElementGuid>9e629596-7ebc-479f-9aa3-915c1dfbbd1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
