<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Users can copy information from the oppor_e6f952</name>
   <tag></tag>
   <elementGuidId>796f6119-c2a9-467c-aac0-802ba33056e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse10']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collapse10 > div.panel-body > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>28dcecd1-d640-43b2-b470-2ac64b9d7f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users can copy information from the opportunity, quotes, project contracts, and forms with the clicking of the Copy button on the command bar.</value>
      <webElementGuid>4befb71c-3439-4d27-8ba9-2814eb31ac8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse10&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>b9a9ba10-e36b-49ed-b35f-eaa424092c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e3a6f75e-118a-434d-a61b-33a67791dd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users can copy information from the opportunity, quotes, project contracts, and forms with the clicking of the Copy button on the command bar.</value>
      <webElementGuid>4a114dc7-40b8-4aac-a5df-ac8c33993e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse10&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>b973b0e3-b66e-427d-8766-7f0e21b5a35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>637ce896-85bb-4fff-a141-c0aafd730e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users can copy information from the opportunity, quotes, project contracts, and forms with the clicking of the Copy button on the command bar.</value>
      <webElementGuid>f15e4b11-e272-4c72-9f0b-f1826e3f4584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse10&quot;)/div[@class=&quot;panel-body&quot;]/p[1]</value>
      <webElementGuid>4233f85e-4c58-459c-8d15-e92fa887952a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse10']/div/p</value>
      <webElementGuid>7eabe990-ebad-4ab4-9347-47129d4d2fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[9]/following::p[1]</value>
      <webElementGuid>b151f5fe-476e-47a3-a141-486cacb73237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='toggle'])[10]/preceding::p[1]</value>
      <webElementGuid>e393e9f1-d0f5-4a9c-918c-adf8deb56c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users can copy information from the opportunity, quotes, project contracts, and forms with the clicking of the Copy button on the command bar.']/parent::*</value>
      <webElementGuid>e0af6420-ac9d-4915-8864-d9d3ef7ef23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/p</value>
      <webElementGuid>1fa294c1-8cfa-48cb-9b0a-b0333ca3c42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Users can copy information from the opportunity, quotes, project contracts, and forms with the clicking of the Copy button on the command bar.' or . = 'Users can copy information from the opportunity, quotes, project contracts, and forms with the clicking of the Copy button on the command bar.')]</value>
      <webElementGuid>f8b61dd6-e491-430f-a8fa-f3f6ee1558bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
