<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_vTiger CRM Solutions</name>
   <tag></tag>
   <elementGuidId>81dc1fbd-29c2-4bb7-9c6c-4ef6822aa7ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='post']/div[2]/div/div/div/div/div[3]/ul[3]/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d944204-102a-4ee4-9fd4-ce91aef79230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://raybiztech.com/solutions/customer-relationship-mgmt/vTiger</value>
      <webElementGuid>80ac3e39-cc40-4f0a-a6b6-e283a2469f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>vTiger CRM Solutions</value>
      <webElementGuid>08380e6a-4aac-4294-9312-5bc5acd7fa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[@id=&quot;post&quot;]/main[@id=&quot;post&quot;]/div[@class=&quot;inner-page-mobile-bg sec-pad&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-9&quot;]/div[@class=&quot;inrtxt&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[4]/a[1]</value>
      <webElementGuid>b3ef6165-da90-4e20-8f30-07005cee0208</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='post']/div[2]/div/div/div/div/div[3]/ul[3]/li[4]/a</value>
      <webElementGuid>d2157052-7a6d-4e50-b199-b327fd78c3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'vTiger CRM Solutions')]</value>
      <webElementGuid>1df31fc1-aeb6-4b5e-a7bd-69348f2e66e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gigya Customer Identity Management'])[2]/following::a[1]</value>
      <webElementGuid>b307831c-2900-4291-9950-5bc0b4fff125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Bpm', &quot;'&quot;, 'online CRM Development')])[1]/following::a[2]</value>
      <webElementGuid>3eb4c22b-c7f5-4f46-b3d2-74e1d610708d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Retention Management'])[1]/preceding::a[1]</value>
      <webElementGuid>349b6816-6dc6-4bc1-806c-85b6ed31295b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead Management'])[1]/preceding::a[2]</value>
      <webElementGuid>1f4f9a2f-60b6-479c-a361-98275abe87b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='vTiger CRM Solutions']/parent::*</value>
      <webElementGuid>1f97cb16-8d47-410f-b047-3da42b01945e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://raybiztech.com/solutions/customer-relationship-mgmt/vTiger')]</value>
      <webElementGuid>acde8778-f712-4c6d-86cb-65b0ebe1f2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li[4]/a</value>
      <webElementGuid>d54cc39f-327e-4723-80dc-4b358c4e746e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://raybiztech.com/solutions/customer-relationship-mgmt/vTiger' and (text() = 'vTiger CRM Solutions' or . = 'vTiger CRM Solutions')]</value>
      <webElementGuid>f246a1c9-776b-48fc-bcc6-c1c1841cd887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
